disable-backpacks: false
end-protection: false

xserver:
  cforward-delay: 60

wormholes:
  enable: true
  period: 3
  count: 30
  offset: 0.5
no-explosion-worlds:
  - "world_the_end"
redis:
  ip: "localhost"
  port: 3306
  username: "default"
  password: ""
  server-name: "spawn"

party:
  tag: "&7[%color%%tag%&7]&r "