name: ARC
version: '${project.version}'
main: arc.arc.ARC
api-version: 1.20
softdepend:
  - Parties
  - Lands
  - CMI
depend:
  - PlaceholderAPI
commands:
  arc:
    description: Main command
    usage: Main command
  mex:
    description: Mex
    usage: mex
  cforward:
    description: cforward
    usage: cforward
  locpool:
    description: locpool
    usage: locpool
  treasure-hunt:
    description: locpool
    usage: locpool
  treasure-item:
    description: locpool
    usage: locpool