name: ARC
version: '${project.version}'
main: arc.arc.ARC
api-version: 1.20
libraries:
  - com.google.code.gson:gson:2.10.1
  - redis.clients:jedis:5.2.0-beta4
  - org.jsoup:jsoup:1.17.2
  - org.eclipse.jetty.websocket:websocket-client:9.4.54.v20240208
softdepend:
  - Parties
  - Lands
  - Citizens
  - CMI
  - WorldGuard
  - EliteMobs
  - HuskHomes
  - ProtectionStones
  - Slimefun
  - EconomyShopGUI-Premium
  - AdvancedEnchantments
  - ItemsAdder
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  - YamipaPlugin
  - LootChest
  - Jobs
  - BetterStructures
  - PlaceholderAPI
commands:
  arc:
    description: Main command
    usage: Main command
  x:
    description: x
    usage: x
  mex:
    description: Mex
    usage: mex
  cforward:
    description: cforward
    usage: cforward
  locpool:
    description: locpool
    usage: locpool
  treasure-hunt:
    description: locpool
    usage: locpool
  treasure-pool:
    description: locpool
    usage: locpool
  build-book:
    description: build-book
    usage: build-book
  em-test:
    description: build-book
    usage: build-book
  arc-invest:
    description: build-book
    usage: build-book
  sound-follow:
    description: build-book
    usage: build-book
  give-jobs-boost:
    description: build-book
    usage: build-book
  arcstore:
    description: build-book
    usage: build-book
  arctest:
    description: build-book
    usage: build-book
  eliteloot:
    description: build-book
    usage: build-book
