name: ARC
version: '${project.version}'
main: arc.arc.ARC
api-version: 1.20
softdepend:
  - Parties
  - Lands
  - CMI
  - WorldGuard
  - EliteMobs
  - HuskHomes
  - ProtectionStones
  - Slimefun
  - EconomyShopGUI-Premium
  - AdvancedEnchantments
  - ItemsAdder
depend:
  - PlaceholderAPI
commands:
  arc:
    description: Main command
    usage: Main command
  mex:
    description: Mex
    usage: mex
  cforward:
    description: cforward
    usage: cforward
  locpool:
    description: locpool
    usage: locpool
  treasure-hunt:
    description: locpool
    usage: locpool
  treasure-pool:
    description: locpool
    usage: locpool