package ru.arc.origin

internal enum class OriginWorkshopGameStage(val step: Int, val instruction: String) {
    STOCK(1, "Возьми заготовку со склада."),
    CARRY_RAW_TO_SAW(2, "Перетащи заготовку к пиле."),
    START_SAW(3, "Нажми рукоять пилы."),
    SAWING(3, "Пила распускает заготовку."),
    SAW_REPOSITION(4, "Разверни доску для второго распила."),
    START_SAW_SECOND(5, "Запусти второй распил рукоятью."),
    SAWING_SECOND(5, "Пила подравнивает второй торец."),
    PICK_SAWN_BOARD(6, "Забери распиленную доску."),
    CARRY_BOARD_TO_DRILL(7, "Положи доску под сверло."),
    START_DRILL(8, "Нажми рукоять сверла."),
    DRILLING(8, "Сверло делает отверстия."),
    DRILL_ALIGN_CENTER(9, "Сдвинь доску к центральной отметке."),
    START_DRILL_SECOND(10, "Опусти сверло для второго отверстия."),
    DRILLING_SECOND(10, "Сверло делает второе отверстие."),
    DRILL_ALIGN_LAST(11, "Сдвинь доску к последней отметке."),
    START_DRILL_THIRD(12, "Опусти сверло для третьего отверстия."),
    DRILLING_THIRD(12, "Сверло делает третье отверстие."),
    PICK_DRILLED_BOARD(13, "Забери просверленную доску."),
    CARRY_BOARD_TO_JIG(14, "Положи доску в сборочный шаблон."),
    LEG_LEFT(15, "Возьми левую ножку."),
    CARRY_LEG_LEFT(16, "Перетащи левую ножку в шаблон."),
    LEG_RIGHT(17, "Возьми правую ножку."),
    CARRY_LEG_RIGHT(18, "Перетащи правую ножку в шаблон."),
    CLAMP_LEFT(19, "Затяни левый зажим."),
    CLAMPING_LEFT(19, "Левый зажим стягивает детали."),
    CLAMP_RIGHT(20, "Затяни правый зажим."),
    CLAMPING_RIGHT(20, "Правый зажим стягивает детали."),
    FINISHING(21, "Готовая мебель просыхает."),
    REWARDING(21, "Готовая мебель отправляется в инвентарь."),
    CLOSED(21, "Сборка завершена."),

    UPHOLSTER_FABRIC(1, "Возьми красную ткань со склада."),
    UPHOLSTER_PLACE_FABRIC(2, "Положи ткань под прижим."),
    UPHOLSTER_STRETCH_LEFT(3, "Растяни ткань к левому борту."),
    UPHOLSTER_STRETCH_RIGHT(4, "Выравняй натяжение у правого борта."),
    UPHOLSTER_START_PRESS(5, "Разгладь ткань прижимом."),
    UPHOLSTER_PRESSING(5, "Прижим выравнивает ткань."),
    UPHOLSTER_PICK_PRESSED_COVER(6, "Забери разглаженную ткань."),
    UPHOLSTER_PLACE_SEWING(7, "Уложи край ткани под иглу машинки."),
    UPHOLSTER_LOWER_SEWING_FOOT(8, "Опусти лапку на ткань."),
    UPHOLSTER_START_SEWING(9, "Поверни маховик: прошей первую кромку."),
    UPHOLSTER_SEWING(9, "Игла прошивает первую кромку."),
    UPHOLSTER_TURN_FABRIC(10, "Разверни ткань и подведи второй край под иглу."),
    UPHOLSTER_START_SEWING_SECOND(11, "Прошей вторую кромку маховиком."),
    UPHOLSTER_SEWING_SECOND(11, "Игла прошивает вторую кромку."),
    UPHOLSTER_PICK_COVER(12, "Забери прошитый чехол с машинки."),
    UPHOLSTER_PLACE_COVER(13, "Надень чехол на основу дивана."),
    UPHOLSTER_PICK_PADDING(14, "Возьми белую набивку."),
    UPHOLSTER_PLACE_PADDING(15, "Уложи набивку под чехол."),
    UPHOLSTER_TUCK_NEAR(16, "Заправь ближний край обивки."),
    UPHOLSTER_TUCK_FAR(17, "Заправь дальний край обивки."),
    UPHOLSTER_FASTEN_LEFT(18, "Закрепи левый борт обивки."),
    UPHOLSTER_FASTEN_RIGHT(19, "Закрепи правый борт обивки."),
    UPHOLSTER_FINISHING(19, "Обивка закреплена на каркасе."),

    ASSEMBLER_STOCK(1, "Возьми заготовку столешницы."),
    ASSEMBLER_PLACE_VISE(2, "Уложи столешницу в тиски."),
    ASSEMBLER_START_VISE(3, "Зажми первую кромку винтовой рукоятью."),
    ASSEMBLER_VISING(3, "Тиски выравнивают первую кромку."),
    ASSEMBLER_ROTATE_TOP(4, "Разверни столешницу в тисках."),
    ASSEMBLER_RETIGHTEN_VISE(5, "Зажми противоположную кромку."),
    ASSEMBLER_VISING_SECOND(5, "Тиски выравнивают вторую кромку."),
    ASSEMBLER_RELEASE_VISE(6, "Освободи столешницу винтовой рукоятью."),
    ASSEMBLER_PICK_VISED(7, "Забери выровненную столешницу."),
    ASSEMBLER_PLACE_ANVIL(8, "Уложи её на сборочную наковальню."),
    ASSEMBLER_START_ANVIL(9, "Ударь молотом по первому соединению."),
    ASSEMBLER_HAMMERING(9, "Молот фиксирует первое соединение."),
    ASSEMBLER_ALIGN_SECOND(10, "Поддержи и разверни столешницу на наковальне."),
    ASSEMBLER_START_ANVIL_SECOND(11, "Ударь молотом по второму соединению."),
    ASSEMBLER_HAMMERING_SECOND(11, "Молот фиксирует второе соединение."),
    ASSEMBLER_PICK_JOINED_TOP(12, "Забери соединённую столешницу."),
    ASSEMBLER_PLACE_ASSEMBLY_TOP(13, "Положи столешницу лицом вниз на верстак."),
    ASSEMBLER_PICK_LEFT_LEG(14, "Возьми левую ножку."),
    ASSEMBLER_PLACE_LEFT_LEG(15, "Посади ножку в левое гнездо."),
    ASSEMBLER_PICK_RIGHT_LEG(16, "Возьми правую ножку."),
    ASSEMBLER_PLACE_RIGHT_LEG(17, "Посади ножку в правое гнездо."),
    ASSEMBLER_TIGHTEN_LEFT(18, "Подтяни левое крепление."),
    ASSEMBLER_CLAMPING_LEFT(18, "Левое крепление стягивает ножку."),
    ASSEMBLER_TIGHTEN_RIGHT(19, "Подтяни правое крепление."),
    ASSEMBLER_CLAMPING_RIGHT(19, "Правое крепление стягивает ножку."),
    ASSEMBLER_FINISHING(19, "Крепления стола осаживаются."),

    FINISHER_START_PANEL(1, "Опусти панель за нижнюю рукоять."),
    FINISHER_WITHDRAWING(1, "Панель ложится на шлифовальную площадку."),
    FINISHER_PICK_ABRASIVE(2, "Возьми шлифовальный брусок."),
    FINISHER_SAND_NEAR(3, "Зачисти ближнюю полосу панели."),
    FINISHER_SAND_CENTER(4, "Зачисти среднюю полосу панели."),
    FINISHER_SAND_FAR(5, "Зачисти дальнюю полосу панели."),
    FINISHER_FLIP_FOR_BACK_SANDING(6, "Переверни панель на необработанную сторону."),
    FINISHER_SAND_BACK_NEAR(7, "Зачисти ближнюю полосу обратной стороны."),
    FINISHER_SAND_BACK_CENTER(8, "Зачисти среднюю полосу обратной стороны."),
    FINISHER_SAND_BACK_FAR(9, "Зачисти дальнюю полосу обратной стороны."),
    FINISHER_DIP_BRUSH(10, "Окуни кисть в защитный состав."),
    FINISHER_COAT_NEAR(11, "Покрой ближнюю полосу."),
    FINISHER_COAT_CENTER(12, "Покрой среднюю полосу."),
    FINISHER_COAT_FAR(13, "Покрой дальнюю полосу."),
    FINISHER_FLIP_FOR_BACK_COAT(14, "Переверни панель покрытой стороной вниз."),
    FINISHER_DIP_BRUSH_SECOND(15, "Снова набери состав на кисть."),
    FINISHER_COAT_BACK_NEAR(16, "Покрой ближнюю полосу обратной стороны."),
    FINISHER_COAT_BACK_CENTER(17, "Покрой среднюю полосу обратной стороны."),
    FINISHER_COAT_BACK_FAR(18, "Покрой дальнюю полосу обратной стороны."),
    FINISHER_HANG_PANEL(19, "Повесь панель на нижнюю перекладину сушилки."),
    FINISHER_DRYING(19, "Защитное покрытие высыхает."),
    FINISHER_FINISHING(19, "Панель готова к установке в мебель.");

    companion object {
        const val TOTAL_STEPS = 21
    }
}

internal enum class OriginWorkshopGameAction {
    PICK_STOCK,
    PLACE_SAW,
    ACTIVATE_SAW,
    REPOSITION_SAW,
    PICK_SAWN_BOARD,
    PLACE_DRILL,
    ACTIVATE_DRILL,
    ALIGN_DRILL_CENTER,
    ALIGN_DRILL_LAST,
    PICK_DRILLED_BOARD,
    PLACE_JIG,
    PICK_LEFT_LEG,
    PLACE_LEFT_LEG,
    PICK_RIGHT_LEG,
    PLACE_RIGHT_LEG,
    TIGHTEN_LEFT,
    TIGHTEN_RIGHT,
    PICK_FABRIC,
    PLACE_FABRIC,
    STRETCH_FABRIC_LEFT,
    STRETCH_FABRIC_RIGHT,
    ACTIVATE_PRESS,
    TURN_FABRIC,
    PICK_PRESSED_COVER,
    PLACE_SEWING,
    LOWER_SEWING_FOOT,
    START_SEWING,
    PICK_SEWN_COVER,
    PLACE_CUSHION_COVER,
    PICK_PADDING,
    PLACE_PADDING,
    TUCK_PADDING_NEAR,
    TUCK_PADDING_FAR,
    FASTEN_COVER_LEFT,
    FASTEN_COVER_RIGHT,
    PICK_TABLETOP,
    PLACE_VISE,
    TIGHTEN_VISE,
    ROTATE_TABLETOP,
    RELEASE_VISE,
    PICK_VISED_TABLETOP,
    PLACE_ANVIL,
    ACTIVATE_ANVIL,
    ALIGN_JOIN_SECOND,
    PICK_JOINED_TABLETOP,
    PLACE_ASSEMBLY_TOP,
    START_FINISH_PANEL,
    PICK_ABRASIVE,
    SAND_PANEL_NEAR,
    SAND_PANEL_CENTER,
    SAND_PANEL_FAR,
    FLIP_PANEL,
    DIP_FINISH_BRUSH,
    COAT_PANEL_NEAR,
    COAT_PANEL_CENTER,
    COAT_PANEL_FAR,
    HANG_FINISHED_PANEL,
}

internal data class OriginWorkshopGameRules(
    val sawTicks: Long = 60,
    val drillTicks: Long = 40,
    val clampTicks: Long = 20,
    val chairHoldTicks: Long = 60,
    val pressTicks: Long = 60,
    val viseTicks: Long = 40,
    val hammerTicks: Long = 60,
    val finishingTicks: Long = 60,
    val timeout: Long = 3_600,
) {
    init {
        require(
            listOf(sawTicks, drillTicks, clampTicks, chairHoldTicks, pressTicks, viseTicks, hammerTicks, finishingTicks)
                .all { it in 1L..1_200L },
        )
        require(timeout in 20L..12_000L)
    }
}

internal data class OriginWorkshopGameProgress(
    val stage: OriginWorkshopGameStage,
    val stageStartedAt: Long = 0,
)

internal data class OriginWorkshopGamePartSize(val x: Float, val y: Float, val z: Float) {
    init {
        require(x.isFinite() && y.isFinite() && z.isFinite() && x > 0f && y > 0f && z > 0f)
    }
}
