package ru.arc.landsui

import me.angeschossen.lands.api.role.Role
import me.angeschossen.lands.api.role.enums.RoleType
import ru.arc.config.Config
import ru.arc.config.ConfigManager
import java.nio.file.Path

data class LandsUiSettings(
    val enabled: Boolean,
    val maxListedPlayers: Int,
    private val text: Map<String, String>,
) {
    fun text(key: String): String = text.getValue(key)

    fun roleName(role: Role): String = when (role.type) {
        RoleType.VISITOR -> text("role-visitor-name")
        RoleType.TENANT -> text("role-tenant-name")
        else -> role.name
    }
}

class LandsUiConfig(private val config: Config) {
    fun snapshot(): LandsUiSettings {
        val maxListedPlayers = config.integer("limits.max-listed-players", 12)
        require(maxListedPlayers in 1..32) { "Lands UI max-listed-players must be in 1..32" }
        return LandsUiSettings(
            enabled = config.bool("enabled", true),
            maxListedPlayers = maxListedPlayers,
            text = DEFAULT_TEXT.mapValues { (key, fallback) ->
                config.string("text.$key", fallback).also { value ->
                    require(value.isNotBlank()) { "Lands UI text '$key' cannot be blank" }
                    require(value.length <= 2_000) { "Lands UI text '$key' is too long" }
                }
            },
        )
    }

    companion object {
        private const val RESOURCE = "lands-ui.yml"

        fun load(dataPath: Path): LandsUiConfig {
            val source = ConfigManager.ofModule(dataPath, RESOURCE)
            source.mergeMissingFromBundled("modules/$RESOURCE")
            return LandsUiConfig(source)
        }

        private val DEFAULT_TEXT = linkedMapOf(
            "role-visitor-name" to "Гость",
            "role-tenant-name" to "Арендатор",
            "role-readonly-body" to "<#e8dfd2>Текущие права роли в регионе <white><area><#e8dfd2>. Здесь доступен просмотр.",
            "native-role-settings-label" to "<#c4a7e7>Настроить права в Lands ›",
            "admin-search-label" to "<#c4a7e7>[Админ] Найти приват ›",
            "admin-search-tooltip" to "<#e8dfd2>Найти поселение по названию или нику главы и участника.",
            "admin-panel-label" to "<#c4a7e7>[Админ] Управление ›",
            "admin-title" to "<#c4a7e7>[Админ] <land>",
            "admin-body" to "<#e8dfd2>Административный режим. Действия относятся к этому привату; доступные кнопки зависят от ваших прав.",
            "admin-search-title" to "<#c4a7e7>Поиск приватов",
            "admin-search-body" to "<#e8dfd2>Введите часть названия поселения или ника главы либо участника. Если результатов много, уточните запрос.",
            "admin-search-input" to "<#e8dfd2>Название или ник",
            "admin-search-results" to "<#e8dfd2>Показано: <white><count><#e8dfd2> · Страница <page> из <pages>",
            "admin-search-entry" to "<#c4a7e7><land> <white>· <owner> ›",
            "search-submit" to "<#9bd48d>Найти",
            "table-area-label" to "<#86dcf1>Регион",
            "management-member-count" to "<white><count> <#e8dfd2>· онлайн <online>",
            "management-description" to "<#e8dfd2>Сообщение при входе: <white><description>",
            "management-members-body" to "<#e8dfd2>Регион: <white><area><newline><#e8dfd2>Участников: <white><members><#e8dfd2> · онлайн <online><newline><#e8dfd2>Страница <page> из <pages>. Нажмите на игрока, чтобы открыть его карточку.",
            "management-member-label" to "<white><player> <#e8dfd2>· <role> · <status> ›",
            "status-online" to "онлайн",
            "status-offline" to "офлайн",
            "member-title" to "<#f3a2c9>Участник · <player>",
            "member-body" to "<#f3a2c9><player> <#e8dfd2>· <status><newline><#e8dfd2>Поселение: <white><land><newline><#e8dfd2>Регион: <white><area><newline><#e8dfd2>Роль: <white><role>",
            "assign-role-label" to "<#c4a7e7>Изменить роль ›",
            "assign-role-title" to "<#c4a7e7>Роль · <player>",
            "assign-role-body" to "<#e8dfd2>Текущая роль: <white><role><newline><#e8dfd2>Регион: <white><area><newline><#e8dfd2>Показаны только роли, которые вы можете назначить.",
            "remove-member-label" to "<#ff8b82>Исключить участника ›",
            "transfer-label" to "<#f4d87a>Предложить передачу владения ›",
            "transfer-title" to "<#f4d87a>Передача владения",
            "transfer-body" to "<#e8dfd2>Предложить игроку <white><player><#e8dfd2> стать главой поселения <white><land><#e8dfd2>?<newline><#e8dfd2>Передача произойдёт после его согласия.<newline><#ff8b82>Текущий глава потеряет права владельца, новый получит полный контроль.",
            "transfer-confirm" to "<#f4d87a>Отправить предложение",
            "rules-label" to "<#86dcf1>Что здесь разрешено ›",
            "rules-title" to "<#86dcf1>Правила · <area>",
            "rules-body" to "<#e8dfd2>Ваши разрешения в этом регионе. Роль: <white><role><newline><#e8dfd2>Правила соседних регионов могут отличаться.",
            "roles-label" to "<#c4a7e7>Роли и права ›",
            "roles-title" to "<#c4a7e7>Роли · <area>",
            "roles-body" to "<#e8dfd2>Откройте роль, чтобы посмотреть её разрешения. Настройка прав доступна через кнопку в карточке роли.",
            "role-entry" to "<#c4a7e7><role> ›",
            "visitor-role-entry" to "<#86dcf1><role> ›",
            "role-title" to "<#c4a7e7>Права · <role>",
            "role-body" to "<#e8dfd2>Регион: <white><area><newline><#e8dfd2>Ниже — текущие права роли. Для изменения откройте настройки Lands, затем «Роли» и эту роль.",
            "rule-enabled" to "<#9bd48d>✔ <rule> · разрешено",
            "rule-disabled" to "<#ffb19a>✕ <rule> · запрещено",
            "environment-label" to "<#9bd48d>Правила территории ›",
            "environment-title" to "<#9bd48d>Территория · <area>",
            "environment-body" to "<#e8dfd2>Эти правила относятся к территории: огню, взрывам и появлению существ. Доступные кнопки переключают правило.",
            "borders-label" to "<#86dcf1>Показать границы",
            "management-territory-body" to "<#e8dfd2>Защищено: <white><chunks>/<max_chunks> чанков<newline><#e8dfd2>Регион: <white><area><newline><#e8dfd2>Расширение и освобождение работают с чанком под вами. Дом — общая точка телепортации поселения.",
            "setspawn-confirm-body" to "<#e8dfd2>Установить дом поселения <white><land><#e8dfd2> там, где вы сейчас стоите?",
            "management-areas-body" to "<#e8dfd2>Выберите основную территорию или отдельный регион для просмотра участников, ролей и правил.",
            "main-area-entry" to "<#9bd48d><area> · основная территория ›",
            "management-settings-label" to "<#f4d87a>Управление поселением ›",
            "management-settings-title" to "<#f4d87a>Управление · <land>",
            "management-settings-body" to "<#e8dfd2>Общие настройки поселения. Для передачи владения выберите участника: ему придёт предложение. Удаление и предложение передачи требуют ввода названия.",
            "description-label" to "<#86dcf1>Сообщение при входе ›",
            "description-title" to "<#86dcf1>Сообщение · <land>",
            "description-body" to "<#e8dfd2>Текст, который Lands показывает при входе на территорию. До 160 символов; пустое поле сбросит сообщение.",
            "description-input" to "<#e8dfd2>Сообщение",
            "save-label" to "<#9bd48d>Сохранить",
            "leave-label" to "<#ffb19a>Покинуть поселение ›",
            "leave-body" to "<#e8dfd2>Покинуть поселение <white><land><#e8dfd2>? Вы потеряете доступ участника. Для возвращения потребуется новое приглашение.",
            "leave-confirm" to "<#ffb19a>Покинуть поселение",
            "confirm-type-name" to "<#e8dfd2>Для подтверждения введите точное название: <white><land>",
            "confirm-name-mismatch" to "<#ff8b82>Название не совпало. Действие не выполнено.",
            "management-saved" to "<#9bd48d>Изменение применено.",
            "management-denied" to "<#ff8b82>У вас нет права на это действие в выбранном регионе.",
            "management-stale" to "<#ff8b82>Данные изменились. Проверьте обновлённое меню и повторите действие.",
            "management-invalid" to "<#ff8b82>Проверьте введённое значение. Изменение не выполнено.",
            "rule-block_break" to "Разрушение блоков",
            "rule-block_place" to "Установка блоков",
            "rule-interact_container" to "Сундуки и хранилища",
            "rule-interact_door" to "Двери",
            "rule-interact_trapdoor" to "Люки",
            "rule-interact_mechanism" to "Кнопки и рычаги",
            "rule-attack_player" to "PvP",
            "rule-attack_animal" to "Урон животным",
            "rule-interact_villager" to "Торговля с жителями",
            "rule-tnt_griefing" to "Разрушения от TNT",
            "rule-fire_spread" to "Распространение огня",
            "rule-monster_spawn" to "Появление монстров",
            "rule-animal_spawn" to "Появление животных",
            "inspect-empty-label" to "<white>[Недоступно] Приват под ногами",
            "admin-menu-label" to "<#c4a7e7>[Админ] Настройки привата ›",
            "admin-menu-tooltip" to "<#e8dfd2>Открыть меню Lands для этого привата: роли, флаги, регионы и остальные настройки.",
            "admin-members-label" to "<#f3a2c9>[Админ] Управлять участниками ›",
            "admin-members-tooltip" to "<#e8dfd2>Открыть управление участниками этого привата в Lands. Права проверяются Lands.",
            "admin-denied" to "<#ff6b61>Нет административного права управлять этим приватом.",
            "inspect-label" to "<#9bd48d>Приват под ногами ›",
            "inspect-tooltip" to "<#e8dfd2>Посмотреть, чья это территория, кто её глава и участники.",
            "location-body" to "<#9bd48d>Вы находитесь: <white><land><newline><#e8dfd2>Глава: <white><owner>",
            "location-empty" to "<#e8dfd2>Под ногами нет привата. Встаньте внутри защищённой территории и откройте этот раздел.",
            "inspect-title" to "<#9bd48d>Приват · <land>",
            "inspect-value" to "<white><value>",
            "inspect-chunks" to "<white><chunks> <#e8dfd2>чанков",
            "table-owner-label" to "<#f3a2c9>Глава",
            "inspect-members-tooltip" to "<#e8dfd2>Глава и полный список участников этого привата.",
            "inspect-owner" to "<#9bd48d>Глава",
            "inspect-member" to "<#e8dfd2>Участник",
            "inspect-members-page" to "<#e8dfd2>Участников: <white><members><#e8dfd2> · Страница <page> из <pages>",
            "inspect-moved" to "<#ff6b61>Вы вышли из этого привата или он был удалён. Сведения обновлены.",
            "manage-label" to "<#c4a7e7>Управлять своим приватом ›",
            "manage-tooltip" to "<#e8dfd2>Выбрать это поселение для быстрых действий.",
            "previous-page" to "<#92bed8>‹ Предыдущая страница",
            "next-page" to "<#92bed8>Следующая страница ›",
            "claim-place-no-permission" to "<#ff8178>Нет права расширять этот приват.",
            "claim-place-working" to "<#e8dfd2>Подожди, захват ещё выполняется.",
            "claim-place-selection-active" to "<#ff8178>Сначала заверши выделение региона.",
            "claim-place-occupied" to "<#ff8178>Этот чанк занят другим приватом.",
            "claim-place-failed" to "<#ff8178>Не всё удалось защитить. Проверь свободное место, лимит и баланс привата.",
            "claim-place-done" to "<#80e89b>Готово. Блок остался в руке.",
            "claim-place-owner" to "<#ff8178>Этот блок привата принадлежит другому игроку.",
            "claim-radius-label" to "<#c4a7e7>Захват <size>×<size> ›",
            "claim-radius-tooltip" to "<#e8dfd2>Выбрать размер следующего захвата этим блоком.",
            "claim-radius-title" to "<#9bd48d>Размер захвата",
            "claim-radius-body" to "<#e8dfd2>Выбери квадрат чанков вокруг места установки.<newline><#e8dfd2>После бесплатной квоты действует обычная плата Lands. Лимиты привата сохраняются.",
            "claim-radius-selected" to "<#9bd48d>✔ <size>×<size> · чанков: <chunks>",
            "claim-radius-option" to "<white>○ <size>×<size> · чанков: <chunks>",
            "claim-display-label" to "<#9bd48d>Отображение подсказки ›",
            "claim-display-tooltip" to "<#e8dfd2>Высота, фиксация, радиус и цвет сетки.",
            "claim-display-title" to "<#9bd48d>Сетка и голограмма",
            "claim-display-body" to "<#e8dfd2>Сетка  <#9bd48d><grid>  •  <radius> чанков<newline><#e8dfd2>Высота  <#e8dfd2><snap><newline><#e8dfd2>Тонкая сетка  <#86dcf1><color><newline><#e8dfd2>Вертикальные линии  <#e8dfd2><posts><newline><#e8dfd2>Голограмма  <#e8dfd2><label><newline><newline><#e8dfd2>Сетка двигается по 1 блоку, голограмма — по 0,5.",
            "claim-display-grid-down" to "<#c4a7e7>Опустить сетку",
            "claim-display-grid-up" to "<#c4a7e7>Поднять сетку",
            "claim-display-label-down" to "<#c4a7e7>Опустить голограмму",
            "claim-display-label-up" to "<#c4a7e7>Поднять голограмму",
            "claim-display-snap" to "<#86dcf1>Высота: <snap> ›",
            "claim-display-snap-smooth" to "плавно",
            "claim-display-snap-blocks" to "по <blocks> бл.",
            "claim-display-radius-down" to "<#c4a7e7>Сетка меньше",
            "claim-display-radius-up" to "<#c4a7e7>Сетка больше",
            "claim-display-color" to "<#86dcf1>Цвет: <color> ›",
            "claim-display-color-ice" to "голубой",
            "claim-display-color-white" to "белый",
            "claim-display-color-purple" to "фиолетовый",
            "claim-display-color-gold" to "золотой",
            "claim-display-color-gray" to "серый",
            "claim-display-posts" to "<#86dcf1>Вертикальные линии: <state> ›",
            "claim-display-enabled" to "включены",
            "claim-display-disabled" to "выключены",
            "claim-display-reset" to "<#e8dfd2>Сбросить всё",
            "claim-display-default" to "обычная высота",
            "claim-display-blocks" to "блока",
            "claim-block-size" to "<#e8dfd2>Захват: <size>×<size> · чанков: <chunks>",
            "claim-block-reusable" to "<#e8dfd2>Многоразовый — поставь на свободной земле.",
            "claim-block-shortcut" to "<#92bed8>[▶] Shift + F <#e8dfd2>— меню приватов",
            "claim-block-missing" to "<#ff8178>Возьми блок привата в руку.",
            "close-label" to "<#ffffff>Закрыть",
            "create-submit-label" to "<#9bd48d>Создать поселение",
            "rename-submit-label" to "<#9bd48d>Сохранить название",
            "add-submit-label" to "<#9bd48d>Добавить игрока",
            "invite-land-label" to "<#9bd48d>Пригласить в <land>",
            "table-land-label" to "Поселение",
            "table-settlements-label" to "<#9bd48d>Поселений",
            "table-selected-label" to "<#86dcf1>Текущее",
            "table-protected-label" to "<#f4d87a>Защищено",
            "table-count-value" to "<#e6fff3><count>",
            "table-selected-value" to "<#e6fff3><land>",
            "table-protected-value" to "<#e6fff3><chunks> <#9fb7c9>чанков",
            "created-table-help" to "<#e8dfd2>Ваш первый чанк уже защищён. Это поселение выбрано текущим.<newline><newline>Для расширения встаньте в соседний чанк и нажмите кнопку ниже.",
            "table-label-heading" to "Параметр",
            "table-value-heading" to "Значение",
            "table-role-label" to "<#9bd48d>Роль",
            "table-territory-label" to "<#86dcf1>Территория",
            "table-members-label" to "<#f3a2c9>Участники",
            "table-balance-label" to "<#f4d87a>Баланс",
            "table-territory-value" to "<#e6fff3><used> <#73808d>/ <#e8dfd2><maximum> <#9fb7c9>чанков",
            "table-slots-value" to "<#e6fff3><used> <#73808d>/ <#e8dfd2><maximum>",
            "table-coins-value" to "<#f4bd6a><value> <white>💰</white>",
            "root-title" to "<#9bd48d>Приват",
            "root-body" to "<#e8dfd2>«Приват под ногами» показывает главу и участников территории, где вы стоите.<newline><#e8dfd2>Ниже — ваши поселения. Выберите одно для управления.",
            "root-empty" to "<#e8dfd2>Своих поселений пока нет. Для создания выберите свободный чанк.",
            "selected-none" to "не выбрано",
            "land-label" to "<white>○ <land> <#c4a7e7>›",
            "land-selected-label" to "<#9bd48d>✔ <land> <#c4a7e7>›",
            "land-tooltip" to "<#e8dfd2><chunks>/<max_chunks> чанков · <members>/<max_members> участников · <balance> монет",
            "create-label" to "<#c4a7e7>Создать поселение ›",
            "create-tooltip" to "<#e8dfd2>Создать поселение в текущем чанке.",
            "guide-label" to "<#86dcf1>Как всё работает ›",
            "guide-tooltip" to "<#e8dfd2>Создание, расширение, участники и команды.",
            "my-lands-label" to "<#c4a7e7>Мои поселения ›",
            "back-label" to "<#ffffff>‹ Назад",
            "invite-picker-title" to "<#9bd48d>Пригласить в поселение",
            "invite-picker-body" to "<#e8dfd2>В какое поселение пригласить игрока <#86dcf1><player><#e8dfd2>?<newline><#e8dfd2>Команда будет выполнена именно для выбранного поселения.",
            "invite-none" to "<#ff6b61>Нет поселения, куда можно пригласить <player>.",

            "details-title" to "<#9bd48d><land>",
            "details-body" to "<#9bd48d>● <#e8dfd2>Роль  <#e8dfd2><role><newline><#86dcf1>◆ <#e8dfd2>Территория  <#e8dfd2><chunks>/<max_chunks> чанков<newline><#9bd48d>◆ <#e8dfd2>Участники  <#e8dfd2><members>/<max_members><newline><#d7b486>◆ <#e8dfd2>Баланс  <#e8dfd2><balance> монет",
            "role-owner" to "<#f4d87a>владелец",
            "role-member" to "<#85dfc4>участник",
            "open-lands-label" to "<#f4d87a>Расширенные настройки ›",
            "open-lands-tooltip" to "<#e8dfd2>Открыть штатные настройки выбранного поселения.",
            "members-label" to "<#f3a2c9>Участники ›",
            "members-tooltip" to "<#e8dfd2>Глава, роли и статус игроков; приглашения и управление составом.",
            "territory-label" to "<#9bd48d>Территория и дом ›",
            "territory-tooltip" to "<#e8dfd2>Чанки, точка дома и главный блок.",
            "region-tool-label" to "<#86dcf1>Мультитул регионов ›",
            "region-tool-tooltip" to "<#e8dfd2>Выделить регион внутри этого поселения.",
            "region-tool-name" to "<#86dcf1>Мультитул регионов",
            "region-tool-lore-first" to "<#e8dfd2>ЛКМ по земле — первый угол",
            "region-tool-lore-second" to "<#e8dfd2>ПКМ по земле — второй угол",
            "region-tool-lore-menu" to "<#e8dfd2>Shift + нажми на кнопку — создать",
            "region-tool-lore-reset" to "<#e8dfd2>Shift + ПКМ мимо кнопки — сбросить",
            "region-inventory-full" to "<#ff6b61>Нет места в инвентаре для мультитула регионов.",
            "region-equipped" to "<#86dcf1>Мультитул регионов выдан. Выберите два угла на земле.",
            "region-select-land" to "<#ff6b61>Сначала выберите поселение в меню привата.",
            "region-controls" to "<#e8dfd2>ЛКМ/ПКМ — углы • Shift + нажми по кнопке • Shift+ПКМ — сброс",
            "region-reset" to "<#e8dfd2>Выделение сброшено.",
            "region-outside" to "<#ff6b61>Всё выделение должно быть внутри поселения <land>.",
            "region-no-permission" to "<#ff6b61>У вас нет права создавать регионы в этом поселении.",
            "region-working" to "<#d7b486>Сохраняем регион в Lands…",
            "region-native-pending" to "<#d7b486>Создание ещё не подтверждено.<newline>  Проверьте список регионов и сообщения Lands.",
            "region-first" to "<#86dcf1>ЛКМ по земле — выберите первый угол",
            "region-second" to "<#86dcf1>ПКМ по земле — выберите второй угол",
            "region-ready" to "<#9bd48d>Готово: <width>×<depth> блоков<newline><land> • на всю высоту мира",
            "region-current" to "<#86dcf1>Регион: <area>",
            "region-create-button" to "<#9bd48d>Shift + нажми — создать регион",
            "region-list-button" to "<#86dcf1>Shift + нажми — список регионов",
            "region-create-title" to "<#c4a7e7>Новый регион",
            "region-create-body" to "<#e8dfd2>Регион будет создан в поселении <#d7b486><land><#e8dfd2>.<newline><#e8dfd2>Размер: <#e8dfd2><width>×<depth> блоков<newline><#e8dfd2>Высота: <#e8dfd2>весь диапазон мира<newline><#e8dfd2>Рамка показывает горизонтальное выделение.",
            "region-name-input" to "<#e8dfd2>Название региона",
            "region-confirm" to "<#9bd48d>Создать регион",
            "region-invalid-name" to "<#ff6b61>Название: 1–24 символа, буквы, цифры, _ или - без пробелов.",
            "region-stale" to "<#ff6b61>Выделение устарело. Выберите углы заново.",
            "region-name-used" to "<#ff6b61>Регион с таким названием уже существует.",
            "region-native-failed" to "<#ff6b61>Не удалось отправить запрос в Lands.<newline>  Попробуйте ещё раз.",
            "region-created" to "<#9bd48d>Регион <area> создан в поселении <land>.",
            "region-list-title" to "<#86dcf1>Регионы · <land>",
            "region-list-body" to "<#e8dfd2>Выберите регион, чтобы открыть его настройки Lands.",
            "region-list-empty" to "<#e8dfd2>В этом поселении пока нет дополнительных регионов.",
            "region-entry" to "<#86dcf1><area> ›",
            "region-previous" to "<#e8dfd2>‹ Назад",
            "region-next" to "<#e8dfd2>Вперёд ›",
            "rename-label" to "<#c4a7e7>Переименовать ›",
            "rename-tooltip" to "<#e8dfd2>Изменить название выбранного поселения.",
            "delete-label" to "<#ff6b61>Удалить поселение ›",
            "delete-tooltip" to "<#e8dfd2>Удалить именно выбранное поселение с подтверждением.",

            "name-input" to "<#e8dfd2>Название",
            "player-input" to "<#e8dfd2>Ник игрока",
            "create-title" to "<#c4a7e7>Новое поселение",
            "create-body" to "<#e8dfd2>Поселение появится там, где вы стоите.<newline><#e8dfd2>Первый чанк защищается автоматически и бесплатно. Новое поселение сразу станет текущим.<newline><newline><#e8dfd2>Название: 5–24 символа, буквы, цифры, _ или - без пробелов.",
            "created-title" to "<#9bd48d>Поселение создано",
            "created-body" to "<#9bd48d><land><newline><#e8dfd2>Ваш первый чанк уже защищён. Это поселение выбрано текущим.<newline><#e8dfd2>Территория: <#e8dfd2><chunks>/<max_chunks> чанков<newline><newline><#e8dfd2>Для расширения встаньте в соседний чанк и нажмите кнопку ниже.",
            "created-claim-label" to "<#9bd48d>Присоединить текущий чанк",
            "created-details-label" to "<#c4a7e7>Открыть поселение ›",
            "create-not-found" to "<#ff6b61>Поселение могло создаться, но меню не успело его определить. Список обновлён.",
            "rename-title" to "<#c4a7e7>Переименовать · <land>",
            "rename-body" to "<#e8dfd2>Введите новое название: 5–24 символа без пробелов.",

            "members-title" to "<#f3a2c9>Участники · <land>",
            "members-body" to "<#e8dfd2>Занято мест: <white><members>/<max_members><newline><#e8dfd2>Выберите игрока, чтобы посмотреть его роль и доступные действия.",
            "add-member-label" to "<#f3a2c9>Добавить игрока ›",
            "member-label" to "<#f3a2c9><player> ›",
            "member-tooltip" to "<#e8dfd2>Убрать <player> из этого поселения.",
            "add-title" to "<#c4a7e7>Добавить · <land>",
            "add-body" to "<#e8dfd2>Выберите игрока онлайн или введите точный ник.<newline><#e8dfd2>Показано до <limit> доступных игроков.",
            "candidate-label" to "<#9bd48d>Добавить <player>",
            "remove-title" to "<#ff6b61>Убрать участника",
            "remove-body" to "<#e8dfd2>Убрать <#d7b486><player> <#e8dfd2>из поселения <#d7b486><land><#e8dfd2>?",
            "remove-confirm-label" to "<#ff6b61><bold>Убрать <player>",

            "territory-title" to "<#9bd48d>Территория · <land>",
            "territory-body" to "<#e8dfd2>Все кнопки ниже относятся только к <#d7b486><land><#e8dfd2>.<newline><#e8dfd2>Для присоединения встаньте в соседний свободный чанк.",
            "claim-label" to "<#9bd48d>Присоединить текущий чанк",
            "claim-tooltip" to "<#e8dfd2>Защитить чанк, в котором вы стоите.",
            "unclaim-label" to "<#ff6b61>Освободить текущий чанк",
            "unclaim-tooltip" to "<#e8dfd2>Снять защиту с чанка, в котором вы стоите.",
            "unclaim-title" to "<#ff6b61>Освободить чанк · <land>",
            "unclaim-body" to "<#e8dfd2>Снять защиту с чанка <#d7b486><chunk_x>, <chunk_z><#e8dfd2> в поселении <#d7b486><land><#e8dfd2>?<newline><#e8dfd2>Команда Lands будет отправлена от вашего имени.",
            "unclaim-confirm-label" to "<#ff6b61>Освободить чанк",
            "unclaim-no-claim" to "<#ff6b61>Вы должны стоять внутри выбранного поселения.",
            "unclaim-stale" to "<#ff6b61>Позиция или поселение изменились. Откройте подтверждение заново.",
            "unclaim-selection-active" to "<#ff6b61>Сначала отключите выделение: <#d7b486>/lands selection",
            "setspawn-label" to "<#9bd48d>Поставить точку дома",
            "setspawn-tooltip" to "<#e8dfd2>Сохранить здесь точку дома поселения.",
            "spawn-label" to "<#92bed8>Телепорт домой ›",
            "spawn-tooltip" to "<#e8dfd2>Переместиться к точке дома поселения.",
            "areas-label" to "<#9bd48d>Дополнительные регионы ›",
            "areas-tooltip" to "<#e8dfd2>Открыть дополнительные регионы Lands.",
            "mainblock-label" to "<#86dcf1>Главный блок и голограмма ›",
            "mainblock-tooltip" to "<#e8dfd2>Инструкция по переносу блока и настройке голограммы.",
            "mainblock-title" to "<#86dcf1>Главный блок · <land>",
            "mainblock-body" to "<#e8dfd2>Чтобы перенести главный блок:<newline><#d7b486>1. <#e8dfd2>Откройте расширенные настройки.<newline><#d7b486>2. <#e8dfd2>Нажмите ЛКМ по колоколу и уберите блок.<newline><#d7b486>3. <#e8dfd2>В новом месте снова откройте меню и установите его.<newline><newline><#e8dfd2>На сервере перенос бесплатный. ПКМ по колоколу переключает голограмму.",

            "guide-title" to "<#86dcf1>Как работают поселения",
            "guide-body" to "<#9bd48d>Поселение <#e8dfd2>— это ваша защищённая территория: набор соседних чанков, участники и общая точка дома.<newline><newline><#86dcf1>Текущее поселение <#e8dfd2>— цель команд Lands. В списке оно отмечено галочкой ✔, а при открытии карточки выбирается явно, поэтому действие не уйдёт в другую землю.<newline><newline><#f4d87a>Быстрые действия <#e8dfd2>в карточке нужны для частых операций: присоединить или освободить чанк, пригласить игрока, переименовать поселение.<newline><newline><#c4a7e7>Разделы ниже <#e8dfd2>собирают более тонкие настройки территории, дома и участников. Перед удалением или освобождением чанка всегда проверяйте название выбранного поселения.<newline><newline><#e8dfd2>Выберите тему — внутри есть порядок действий, ограничения и безопасный следующий шаг.",
            "guide-create-label" to "<#9bd48d>Создание ›",
            "guide-create-tooltip" to "<#e8dfd2>Как основать новое поселение.",
            "guide-expand-label" to "<#86dcf1>Расширение территории ›",
            "guide-expand-tooltip" to "<#e8dfd2>Как правильно присоединять новые чанки.",
            "guide-members-label" to "<#f3a2c9>Участники ›",
            "guide-members-tooltip" to "<#e8dfd2>Как добавлять и исключать игроков.",
            "guide-commands-label" to "<#c4a7e7>Команды Lands ›",
            "guide-commands-tooltip" to "<#e8dfd2>Короткая памятка по ручным командам.",
            "guide-create-title" to "<#86dcf1>Создание поселения",
            "guide-create-body" to "<#9bd48d>Перед созданием<newline><#e8dfd2>Выберите постоянное место для базы и встаньте в нужный чанк. Проверьте, что он свободен от чужой защиты.<newline><newline><#f4d87a>Порядок действий<newline><#e8dfd2>1. Нажмите «Создать поселение» и введите название.<newline>2. Первый чанк присоединится автоматически и бесплатно.<newline>3. Новое поселение станет текущим; откроется карточка результата.<newline>4. Для расширения переходите в соседние свободные чанки по одному.<newline><newline><#86dcf1>Важно<newline><#e8dfd2>Остальная местность не защищается автоматически. Границы каждого чанка можно проверить подсветкой.",
            "guide-expand-title" to "<#86dcf1>Расширение территории",
            "guide-expand-body" to "<#86dcf1>Как расширять<newline><#e8dfd2>1. Откройте нужное поселение — оно станет текущим.<newline>2. Встаньте в соседний свободный чанк.<newline>3. В карточке нажмите «Присоединить текущий чанк».<newline>4. Сверьте новый размер территории в таблице.<newline><newline><#f4d87a>Стоимость и лимит<newline><#e8dfd2>Первый чанк бесплатный. Следующие стоят монет, цена постепенно растёт; доступный лимит всегда виден в карточке.<newline><newline><#ff8b82>Освобождение<newline><#e8dfd2>Снимает защиту именно с чанка под вами и требует подтверждения. Убедитесь, что внутри не останется важная постройка.<newline><newline><#c4a7e7>Ручная команда: <#e8dfd2>/lands claim. Обычная /claim для расширения не подходит.",
            "guide-members-title" to "<#86dcf1>Участники",
            "guide-members-body" to "<#f3a2c9>Добавить игрока<newline><#e8dfd2>Откройте карточку поселения и нажмите «Добавить игрока». Можно выбрать игрока онлайн или ввести точный ник.<newline><newline><#86dcf1>Управление составом<newline><#e8dfd2>Раздел «Участники» показывает главу, роли и статус игроков. В карточке участника можно назначить доступную роль или исключить его с подтверждением.<newline><newline><#f4d87a>Права<newline><#e8dfd2>В «Роли и права» настраиваются разрешения выбранного региона. «Что здесь разрешено» показывает ваши права, включая двери, сундуки, строительство и PvP.",
            "guide-commands-title" to "<#86dcf1>Команды Lands",
            "guide-commands-body" to "<#86dcf1>Выбрать поселение<newline><#e8dfd2>/lands edit НАЗВАНИЕ<newline><newline><#9bd48d>Присоединить текущий чанк<newline><#e8dfd2>/lands claim<newline><newline><#f3a2c9>Добавить игрока<newline><#e8dfd2>/lands trust НИК<newline><newline><#f4d87a>Открыть полные настройки<newline><#e8dfd2>/lands menu<newline><newline><#ff8b82>Удалить выбранное поселение<newline><#e8dfd2>/lands delete<newline><newline><#ff8b82>Перед опасной командой обязательно проверьте текущее поселение и прочитайте подтверждение.",

            "danger-title" to "<#ff6b61>Удаление · <land>",
            "danger-body" to "<#ff6b61><bold>Это необратимое действие.<newline><#e8dfd2>Будет удалено именно поселение <#d7b486><land><#e8dfd2>. Территория перестанет быть защищённой.",
            "delete-confirm-label" to "<#ff6b61><bold>Удалить навсегда",
            "invalid-name" to "<#ff6b61>Название: 5–24 символа, буквы, цифры, _ или - без пробелов.",
            "invalid-player" to "<#ff6b61>Ник должен содержать 3–16 латинских букв, цифр или _.",
            "land-gone" to "<#ff6b61>Поселение больше недоступно. Список обновлён.",
            "action-failed" to "<#ff6b61>Команда Lands не выполнилась.",
        )
    }
}
