id: produce_multiplier
name: "Produce Multiplier"
type: basic
levels:
  1:
    name: "Level 1"
    min-level: 1
    produce-multiplier: 1.1
    consume-multiplier: 1.1
  2:
    name: "Level 2"
    min-level: 1
    produce-multiplier: 2.0
    consume-multiplier: 2.0