package ru.arc.helpcenter

import ru.arc.config.Config
import ru.arc.config.ConfigManager
import java.nio.file.Path

data class HelpCenterCommandText(
    val label: String,
    val description: String,
    val keywords: String,
)

data class HelpCenterIntentText(
    val label: String,
    val description: String,
    val keywords: String,
)

data class HelpCenterSettings(
    val enabled: Boolean,
    val maxHomes: Int,
    val maxSearchResults: Int,
    val loadTimeoutSeconds: Long,
    private val text: Map<String, String>,
    private val commands: Map<String, HelpCenterCommandText>,
    private val intents: Map<String, HelpCenterIntentText>,
) {
    fun text(key: String): String = text.getValue(key)

    fun command(id: String): HelpCenterCommandText = commands.getValue(id)

    fun intent(id: String): HelpCenterIntentText = intents.getValue(id)
}

class HelpCenterConfig(private val config: Config) {
    fun snapshot(): HelpCenterSettings {
        val maxHomes = config.integer("limits.max-homes", 12)
        val maxSearchResults = config.integer("limits.max-search-results", 8)
        val loadTimeoutSeconds = config.long("limits.load-timeout-seconds", 3)
        require(maxHomes in 1..32) { "Help center max-homes must be in 1..32" }
        require(maxSearchResults in 1..32) { "Help center max-search-results must be in 1..32" }
        require(loadTimeoutSeconds in 1..10) { "Help center load-timeout-seconds must be in 1..10" }
        return HelpCenterSettings(
            enabled = config.bool("enabled", true),
            maxHomes = maxHomes,
            maxSearchResults = maxSearchResults,
            loadTimeoutSeconds = loadTimeoutSeconds,
            text = DEFAULT_TEXT.mapValues { (key, fallback) -> required("text.$key", fallback) },
            commands = COMMANDS.mapValues { (id, fallback) ->
                HelpCenterCommandText(
                    label = required("commands.$id.label", fallback.label),
                    description = required("commands.$id.description", fallback.description),
                    keywords = required("commands.$id.keywords", fallback.keywords),
                )
            },
            intents = INTENTS.mapValues { (id, fallback) ->
                HelpCenterIntentText(
                    label = required("intents.$id.label", fallback.label),
                    description = required("intents.$id.description", fallback.description),
                    keywords = required("intents.$id.keywords", fallback.keywords),
                )
            },
        )
    }

    private fun required(path: String, fallback: String): String = config.string(path, fallback).also { value ->
        require(value.isNotBlank()) { "Help center value '$path' cannot be blank" }
        require(value.length <= 2_000) { "Help center value '$path' is too long" }
    }

    companion object {
        private const val RESOURCE = "help-center.yml"

        fun load(dataPath: Path): HelpCenterConfig {
            val source = ConfigManager.ofModule(dataPath, RESOURCE)
            source.mergeMissingFromBundled("modules/$RESOURCE")
            return HelpCenterConfig(source)
        }

        private val DEFAULT_TEXT = linkedMapOf(
            "menu-close-label" to "<#aaa49a>Закрыть меню",
            "settings-flight-back-label" to "<#aaa49a>‹ Полёт и подзарядка",
            "settings-flight-auto-off-help" to "<#e8dfd2>Отключение сохранит накопленный заряд.<newline><#aaa49a>Режим полёта включается на предыдущем экране.",
            "settings-flight-auto-current" to "<#aaa49a>Настройки / Полёт / Автопополнение<newline><#e8dfd2>Выбран способ: <state>",
            "settings-flight-auto-label" to "<#d7b486>Автопополнение: <state><#d7b486> ›",
            "settings-flight-unavailable" to "<#aaa49a>Запас заряда и состояние полёта недоступны.<newline>Откройте раздел позже, чтобы обновить данные.",
            "settings-flight-status" to "<#e4b878>Запас заряда<newline><#9bd48d><filled><#aaa49a><empty>  <#e8dfd2><percent>%<newline><#e8dfd2><charge> / <maximum><#aaa49a>    Полёт: <state>",
            "settings-flight-unavailable-label" to "<#aaa49a>Полёт: неизвестно",
            "settings-flight-disable-label" to "<#d7b486>Выключить полёт",
            "settings-flight-enable-label" to "<italic:false><#9bd48d>Включить полёт",
            "settings-flight-how" to "<italic:false><#e8dfd2>Заряд расходуется при движении в воздухе и зависании.<newline>Для взлёта включите полёт и дважды нажмите прыжок.<newline><#aaa49a>Нужны доступ к полёту и оставшийся заряд.",
            "settings-flight-breadcrumb" to "<italic:false><#aaa49a>Настройки / Мир и перемещение / Полёт",
            "settings-flight-title" to "<italic:false><#835326>Полёт и подзарядка",
            "settings-portal-style-option-tooltip" to "<#e8dfd2>Оформление: <state><newline><newline><#d7b486>Нажмите, чтобы выбрать этот вид портала.",
            "settings-options-flight-body" to "<#e8dfd2>Выберите ресурс для автоматической покупки заряда.",
            "settings-options-flight-title" to "<#835326>Автопополнение заряда",
            "settings-options-portal-style-body" to "<#e8dfd2>Выберите оформление создаваемого портала.<newline>Галочка отмечает текущий стиль.",
            "settings-options-portal-style-title" to "<#835326>Вид портала",
            "settings-options-lands-body" to "<#e8dfd2>Покажите границы территории рядом с собой<newline>или отключите их подсветку.",
            "settings-options-lands-title" to "<#835326>Границы земель",
            "settings-options-tablist-body" to "<#e8dfd2>Выберите оформление списка игроков по клавише Tab.<newline>«Выключить» уберёт дополнительное оформление.",
            "settings-options-tablist-title" to "<#835326>Список игроков",
            "settings-options-scoreboard-body" to "<#e8dfd2>Выберите набор информации справа на экране.<newline>«Выключить» полностью скроет панель.",
            "settings-options-scoreboard-title" to "<#835326>Информационная панель",
            "settings-options-escape-body" to "<#e8dfd2>Закрыть — выйти из всех меню.<newline>Назад — вернуться к предыдущему экрану.",
            "settings-options-escape-title" to "<#835326>Поведение Escape",
            "settings-options-shortcut-body" to "<#e8dfd2>Выберите действие для сочетания Shift + F.<newline>Обычная клавиша F продолжит менять предметы в руках.",
            "settings-options-shortcut-title" to "<#835326>Горячая клавиша Shift + F",
            "settings-options-body" to "<#aaa49a>Сейчас: <#e8dfd2><state>",
            "settings-selected-option" to "<#9bd48d>✔ <label>",
            "settings-trails-unavailable-tooltip" to "<#e8dfd2>Состояние тропинок на этом сервере недоступно.<newline><#aaa49a>Кнопка не меняет настройки.<newline>Попробуйте открыть раздел позже или на другом сервере.",
            "settings-unavailable-state" to "<#aaa49a>недоступно",
            "settings-back-label" to "<#aaa49a>‹ В настройки",
            "settings-hub-body" to "<#e8dfd2>Настройте игру под себя.<newline><#aaa49a>Shift + F: <#e8dfd2><shortcut><#aaa49a>    Escape: <#e8dfd2><escape>",
            "settings-world-tooltip" to "<italic:false><#e8dfd2>Тропинки, границы земель и полёт.<newline>Доступ к порталам и их оформление.",
            "settings-world-label" to "<italic:false><#d7b486>Мир и перемещение ›",
            "settings-social-tooltip" to "<italic:false><#e8dfd2>Канал чата, уведомления и запросы телепортации.",
            "settings-social-label" to "<italic:false><#d7b486>Общение ›",
            "settings-interface-tooltip" to "<italic:false><#e8dfd2>Информационная панель и список игроков.<newline>Частицы, ресурспак и полоса автототема.",
            "settings-interface-label" to "<italic:false><#d7b486>Интерфейс ›",
            "settings-controls-tooltip" to "<italic:false><#e8dfd2>Горячая клавиша и поведение Escape.<newline>Редактирование табличек и посадка на ступеньки.",
            "settings-controls-label" to "<italic:false><#d7b486>Управление ›",
            "settings-world-back-label" to "<#aaa49a>‹ Мир и перемещение",
            "settings-world-body" to "<italic:false><#aaa49a>Настройки / Мир и перемещение<newline><italic:false><#e8dfd2>Тропинки, полёт и взаимодействие с территориями.",
            "settings-world-title" to "<italic:false><#835326>Мир и перемещение",
            "settings-social-back-label" to "<#aaa49a>‹ Общение",
            "settings-social-body" to "<italic:false><#aaa49a>Настройки / Общение<newline><italic:false><#e8dfd2>Кто вас слышит и какие сообщения вы получаете.",
            "settings-social-title" to "<italic:false><#835326>Общение",
            "settings-interface-back-label" to "<#aaa49a>‹ Интерфейс",
            "settings-interface-body" to "<italic:false><#aaa49a>Настройки / Интерфейс<newline><italic:false><#e8dfd2>Информация на экране и визуальные эффекты.",
            "settings-interface-title" to "<italic:false><#835326>Интерфейс",
            "settings-controls-back-label" to "<#aaa49a>‹ Управление",
            "settings-controls-body" to "<italic:false><#aaa49a>Настройки / Управление<newline><italic:false><#e8dfd2>Выберите привычные клавиши и действия.",
            "settings-controls-title" to "<italic:false><#835326>Управление",
            "legacy-action-flight-recharge-tooltip" to "<#e6fff3>Меню ручного пополнения запаса полёта.<newline><#969696>В нём можно выбрать опыт или игровые деньги<newline>и посмотреть стоимость доступного количества.<newline>Покупка заряда выполняется в этом меню.<newline><newline><#d7b486>Нажмите, чтобы открыть пополнение.",
            "legacy-action-flight-toggle-tooltip" to "<#e6fff3>Включить или выключить режим полёта за заряд.<newline><#969696>Для взлёта дважды нажмите прыжок.<newline>Нужны доступ к полёту и оставшийся заряд.<newline>Эта кнопка не выбирает способ подзарядки.<newline><newline><#d7b486>Нажмите, чтобы переключить режим полёта.",
            "legacy-action-flight-off-tooltip" to "<#e6fff3>Отключить автоматическую покупку заряда.<newline><#969696>Опыт и деньги перестанут тратиться<newline>на автопополнение. Накопленный заряд сохранится,<newline>и его можно будет использовать для полёта.<newline><newline><#d7b486>Нажмите, чтобы выключить автоподзарядку.",
            "legacy-action-flight-money-tooltip" to "<#e6fff3>Автоматически пополнять заряд за игровые деньги.<newline><#969696>Когда запас снизится, деньги будут списываться<newline>с вашего баланса без отдельного нажатия.<newline>Автопополнение за опыт будет выключено.<newline><newline><#d7b486>Нажмите, чтобы выбрать оплату деньгами.",
            "legacy-action-flight-exp-tooltip" to "<#e6fff3>Автоматически пополнять заряд за очки опыта.<newline><#969696>Когда запас снизится, опыт будет списываться<newline>без отдельного нажатия. Это очки, а не уровни.<newline>Автопополнение за деньги будет выключено.<newline><newline><#d7b486>Нажмите, чтобы выбрать оплату опытом.",
            "flight-body-start" to "<#f4bd6a>Как взлететь<newline><#e6fff3>Включите режим кнопкой «Переключить полёт», затем дважды нажмите прыжок. Нужны доступ к полёту и запас заряда. Настройка подзарядки сама по себе их не выдаёт.",
            "flight-body-recharge" to "<#f4bd6a>Автоподзарядка<newline><#e6fff3>При низком запасе заряд пополняется за выбранный ресурс: очки опыта или игровые деньги. Ресурс списывается автоматически. Режим «выкл» отключает только автопополнение.",
            "flight-body-how" to "<#f4bd6a>Как работает полёт<newline><#e6fff3>Это полёт с запасом заряда: он расходуется, пока вы летите или зависаете в воздухе. Остаток показывает полоса вверху экрана.",
            "setting-trails-off-tooltip" to "<#e6fff3>Ваши шаги участвуют в создании тропинок.<newline><#969696>Повторные проходы меняют подходящую землю<newline>и постепенно прокладывают маршрут.<newline>Выключение не убирает уже созданные тропы.<newline><newline><#d7b486>Нажмите, чтобы больше не протаптывать землю.",
            "setting-trails-on-tooltip" to "<#e6fff3>Повторные проходы постепенно протаптывают землю.<newline><#969696>Подходящие блоки меняются по стадиям,<newline>и на часто используемом маршруте появляется тропа.<newline><newline><#d7b486>Нажмите, чтобы ваши шаги создавали тропинки.",
            "setting-particles-tooltip" to "<#e6fff3>Видимость эффектов PlayerParticles.<newline><#969696>Отключите их, если частицы отвлекают,<newline>или включите, чтобы снова видеть эффекты.<newline>Настройка меняет их отображение для вас.<newline><newline><#d7b486>Нажмите, чтобы показать или скрыть частицы.",
            "setting-chat-local-tooltip" to "<#e6fff3>Локальный чат для общения поблизости.<newline><#969696>Ваши сообщения увидят игроки рядом.<newline>Подходит для разговора в одном месте.<newline><newline><#d7b486>Нажмите, чтобы писать в локальный чат.",
            "setting-chat-global-tooltip" to "<#e6fff3>Глобальный чат для общего общения.<newline><#969696>Сообщения отправляются в общий канал,<newline>даже если собеседник далеко от вас.<newline><newline><#d7b486>Нажмите, чтобы писать в глобальный чат.",
            "legacy-settings-portal-for-other-tooltip" to "<#e6fff3>Доступ других игроков к вашим порталам.<newline><#969696>Включено — разрешаете гостям использовать<newline>ваши порталы. Выключено — закрываете доступ.<newline>У гостя также должны быть включены чужие порталы.<newline><newline><#d7b486>Нажмите, чтобы переключить разрешение.",
            "legacy-settings-portal-by-other-tooltip" to "<#e6fff3>Использование порталов других игроков.<newline><#969696>Включено — вы разрешаете перемещать себя<newline>через чужие порталы, если владелец их открыл.<newline>Выключено — такие переходы запрещены.<newline><newline><#d7b486>Нажмите, чтобы переключить разрешение.",
            "legacy-settings-shortcut" to "<#d7b486>Shift + F: <state><#d7b486> ›",
            "legacy-settings-shortcut-tooltip" to "<#e6fff3>Выберите действие для Shift + F.<newline><#969696>Если вы сменили клавиши управления: приседание + смена рук.<newline>Выбор сохраняется между серверами. Обычная F не меняется.",
            "legacy-settings-escape" to "<#d7b486>Escape: <state><#d7b486> ›",
            "legacy-settings-escape-tooltip" to "<#e6fff3>Закрыть все меню или вернуться на предыдущий экран.<newline><#969696>По умолчанию — закрыть всё. Кнопка «Назад» доступна в обоих режимах.",
            "setting-selected" to "<#9cdb67>✔ ",
            "shortcut-unavailable" to "<#ff6b61>Назначенное действие сейчас недоступно. Выберите другое в настройках меню.",
            "escape-state-close" to "закрыть всё",
            "escape-state-back" to "назад",
            "legacy-action-escape-close" to "<#d7b486>Закрыть все меню",
            "legacy-action-escape-close-tooltip" to "<#e6fff3>Escape сразу возвращает в игру.<newline><#969696>Режим по умолчанию.",
            "legacy-action-escape-back" to "<#d7b486>Вернуться назад",
            "legacy-action-escape-back-tooltip" to "<#e6fff3>Escape выполняет действие кнопки «Назад».<newline><#969696>В главном меню — закрывает меню.",
            "shortcut-state-main" to "главное меню",
            "legacy-action-shortcut-main" to "<#d7b486>Главное меню",
            "legacy-action-shortcut-main-tooltip" to "<#e6fff3>Открыть главное меню сервера. Назначение по умолчанию.",
            "shortcut-state-mount" to "любимый маунт",
            "legacy-action-shortcut-mount" to "<#d7b486>Любимый маунт",
            "legacy-action-shortcut-mount-tooltip" to "<#e6fff3>Призвать выбранного любимого маунта. Выберите его заранее в /mount.",
            "shortcut-state-travel" to "телепортация и дома",
            "legacy-action-shortcut-travel" to "<#d7b486>Телепортация и дома",
            "legacy-action-shortcut-travel-tooltip" to "<#e6fff3>Открыть дома и доступные точки путешествий.",
            "shortcut-state-favorites" to "избранное",
            "legacy-action-shortcut-favorites" to "<#d7b486>Избранное",
            "legacy-action-shortcut-favorites-tooltip" to "<#e6fff3>Открыть закреплённые и недавно использованные действия.",
            "shortcut-state-settings" to "настройки",
            "legacy-action-shortcut-settings" to "<#d7b486>Настройки",
            "legacy-action-shortcut-settings-tooltip" to "<#e6fff3>Открыть личные настройки сервера.",
            "shortcut-state-disabled" to "не использовать",
            "legacy-action-shortcut-disabled" to "<#d7b486>Не использовать",
            "legacy-action-shortcut-disabled-tooltip" to "<#e6fff3>Shift + F выполняет обычную смену предметов между руками.",
            "diagnostic-title" to "<#f4bd6a><problem>",
            "category-empty" to "<#969696>В этом разделе пока нет доступных действий.<newline>Попробуйте поиск или другой раздел.",
            "diagnostic-command-failed-help" to "<#e6fff3>Найдите действие через поиск — там есть описание и точная команда.<newline>Проверьте последнее сообщение чата: в нём может быть причина отказа.<newline><#969696>Недоступный на этом сервере раздел может отсутствовать в каталоге.",
            "diagnostic-lost-item-help" to "<#e6fff3>Возьмите предмет в основную руку и откройте его карточку.<newline>Для дополнительных предметов доступен рецепт, если его предоставляет каталог.<newline><#969696>Переход в магазин или на аукцион сам по себе ничего не продаёт.",
            "diagnostic-cannot-find-player-help" to "<#e6fff3>Откройте «Игроки», выберите всю сеть и сбросьте поиск.<newline>Попробуйте часть ника, затем обновите список.<newline><#969696>В списке показаны только игроки онлайн.",
            "diagnostic-cannot-claim-help" to "<#e6fff3>Выберите своё поселение в разделе «Приват».<newline>Проверьте лимит чанков, доступный баланс и права на расширение.<newline><#969696>Чужую территорию занять нельзя. Подробный отказ покажет Lands.",
            "diagnostic-cannot-teleport-help" to "<#e6fff3>Не двигайтесь во время отсчёта телепортации.<newline>Проверьте сохранённые дома или отправьте другу новый запрос.<newline><#969696>Если команда отказала, причина будет в последнем сообщении чата.",
            "goal-together-body" to "<#e6fff3>Найдите друга в сети: можно написать, позвать к себе или пригласить в приват.<newline><#969696>События и дуэли помогут выбрать совместное занятие.",
            "goal-develop-body" to "<#e6fff3>Откройте ранг, чтобы увидеть условия следующего повышения.<newline><#969696>Работы, задания и навыки дают отдельные цели для развития.",
            "goal-fight-body" to "<#e6fff3>Дуэли — для боя с игроком, данжи — для приключений с противниками.<newline><#969696>Условия участия и награды показаны внутри выбранной активности.",
            "goal-explore-body" to "<#e6fff3>Выберите мир или готовую точку для путешествия.<newline><#969696>Перед дальней дорогой сохраните дом в разделе «Телепортация».",
            "goal-build-body" to "<#e6fff3>Сначала защитите место для базы, затем выбирайте материалы и инструменты.<newline><#969696>В технологиях есть механизмы, а в каталоге — дополнительные предметы.",
            "goal-earn-body" to "<#e6fff3>Работы платят за игровые действия, а магазины выкупают ресурсы.<newline><#969696>Редкие вещи можно предложить другим игрокам на аукционе.",
            "favorites-picker-body" to "<#e6fff3>Выберите раздел, затем нужное действие.<newline><#969696>В его карточке нажмите «Добавить в избранное».",
            "favorites-picker-title" to "<#f4bd6a>Добавить в избранное",
            "favorites-full" to "<#e6fff3>Все четыре места заняты.<newline><#e6fff3>Уберите ненужное действие в избранном, чтобы закрепить новое.",
            "action-unavailable" to "<#ff6b61>Действие сейчас недоступно. Откройте раздел заново.",
            "page-next-label" to "<#d7b486>Следующая →",
            "page-previous-label" to "<#d7b486>← Предыдущая",
            "refresh-tooltip" to "<#e6fff3>Загрузить актуальный список, сохранив фильтр.",
            "refresh-label" to "<#d7b486>Обновить",
            "players-clear-label" to "<#d7b486>Сбросить поиск",
            "players-local-label" to "<#d7b486>Только мой сервер",
            "players-network-label" to "<#d7b486>Вся сеть",
            "players-all-servers" to "вся сеть",
            "root-title" to "<italic:false><#835326>Главное меню",
            "root-body" to "<italic:false><#e8dfd2>Всё для игры — в одном месте.<newline><#aaa49a>Выберите раздел; наведите на кнопку для подробностей.",
            "now-label" to "<italic:false><#86dcf1>Мой профиль ›",
            "now-tooltip" to "<#e6fff3>Ваше состояние и полезные следующие шаги.",
            "players-label" to "<italic:false><#f3a2c9>Игроки ›",
            "players-tooltip" to "<#e6fff3>Телепорт, сообщение, перевод, дуэль или приглашение.",
            "my-label" to "<#d7b486>Про меня",
            "my-tooltip" to "<#e6fff3>Ваш профиль, дома, поселения и прогресс.",
            "guide-label" to "<#d7b486>С чего начать",
            "guide-tooltip" to "<#e6fff3>Первые шаги без лишних команд.",
            "commands-label" to "<italic:false><#aaa49a>Поиск ›",
            "commands-tooltip" to "<#e6fff3>Найти действие обычной фразой.",
            "travel-label" to "<italic:false><#91c4ff>Телепортация ›",
            "travel-tooltip" to "<#e6fff3>Дома, миры, варпы и возврат.",
            "privat-label" to "<italic:false><#a3de92>Приват ›",
            "privat-tooltip" to "<#e6fff3>Создание, территория, участники и подробный гайд.",
            "main-menu-label" to "<#969696>Главное меню",
            "main-menu-tooltip" to "<#e6fff3>Открыть остальные игровые разделы сервера.",
            "back-label" to "<#aaa49a>‹ Назад",
            "root-label" to "<#aaa49a>‹ Главное меню",
            "not-available" to "—",
            "now-title" to "<#835326>Мой профиль",
            "now-identity" to "<#e6fff3><player><newline><#969696>Сервер: <#e6fff3><server> <#969696>· Онлайн: <#e6fff3><online>",
            "now-progress" to "<#969696>Ранг: <#e6fff3><rank><newline><#969696>Баланс: <#e6fff3><balance><newline><#969696>Дома: <#e6fff3><homes>/<max_homes> <#969696>· Приваты: <#e6fff3><lands>",
            "now-location" to "<#969696>Мир: <#e6fff3><world><newline><#969696>Координаты: <#e6fff3><x>, <y>, <z><newline><#969696>Чат: <#e6fff3><chat>",
            "rec-home-label" to "<#d7b486>Поставить первый дом",
            "rec-land-label" to "<#d7b486>Защитить территорию",
            "rec-rank-label" to "<#d7b486>Следующая цель ранга",
            "rec-bp-label" to "<#d7b486>Боевой пропуск",
            "rec-events-label" to "<#d7b486>Текущие события",
            "favorites-short-label" to "<#d7b486>Избранное и недавнее",
            "favorites-tooltip" to "<#e6fff3>Закреплённые и последние действия.",
            "favorites-title" to "<#f4bd6a>Избранное и недавнее",
            "personalization-loading" to "<#e6fff3>Загружаю ваши действия…",
            "personalization-unavailable" to "<#e6fff3>Избранное сейчас недоступно, но остальные разделы работают.",
            "favorites-body" to "<#e6fff3>Избранное: <#e6fff3><favorites>/4<newline><#969696>★ — закреплено · ↻ — недавно использовано<newline>Выберите действие, чтобы открыть его или убрать из избранного.",
            "favorite-command-label" to "<#d7b486>★ <label>",
            "recent-command-label" to "<#d7b486>↻ <label>",
            "favorite-find-label" to "<#d7b486>Выбрать из каталога",
            "action-title" to "<#f4bd6a><action>",
            "action-body" to "<#e6fff3><description><newline><#969696>Команда: /<command>",
            "action-run-label" to "<#2bba43>Выполнить",
            "favorite-add-label" to "<#2bba43>Добавить в избранное",
            "favorite-remove-label" to "<#969696>Убрать из избранного",
            "goals-short-label" to "<#d7b486>Чем заняться",
            "goals-tooltip" to "<#e6fff3>Подобрать игровые действия под вашу цель.",
            "goals-title" to "<#f4bd6a>Чем заняться",
            "goals-body" to "<#e6fff3>Выберите, чего хочется сейчас.<newline><#969696>Покажу несколько подходящих возможностей без лишнего списка.",
            "goal-earn-label" to "<#d7b486>Заработать",
            "goal-build-label" to "<#d7b486>Строить",
            "goal-explore-label" to "<#d7b486>Исследовать",
            "goal-fight-label" to "<#d7b486>Сражаться",
            "goal-develop-label" to "<#d7b486>Развиваться",
            "goal-together-label" to "<#d7b486>Играть вместе",
            "goal-title" to "<#f4bd6a><goal>",
            "goal-body" to "<#e6fff3>Вот короткий набор подходящих действий.",
            "context-short-label" to "<#d7b486>Что рядом со мной",
            "context-tooltip" to "<#e6fff3>Мир, приват, предмет в руке и полезные действия.",
            "context-title" to "<#f4bd6a>Что рядом со мной",
            "context-body" to "<#e6fff3>◆ <#969696>Мир  <#e6fff3><world><newline><#e6fff3>◆ <#969696>Сервер  <#e6fff3><server><newline><#e6fff3>◆ <#969696>Координаты  <#e6fff3><coordinates><newline><#e6fff3>◆ <#969696>Приват  <#e6fff3><land><newline><#e6fff3>◆ <#969696>В руке  <#e6fff3><item>",
            "context-item-label" to "<#d7b486>Предмет в руке",
            "item-tooltip" to "<#e6fff3>Рецепт, каталог, торговля и улучшения предмета.",
            "item-title" to "<#f4bd6a>Предмет в руке",
            "item-empty" to "<#e6fff3>Возьмите предмет в основную руку и откройте этот экран снова.",
            "item-body" to "<#e6fff3><item><newline><#969696>Количество: <#e6fff3><amount><newline><#969696>Тип: <#e6fff3><kind>",
            "item-recipe-label" to "<#d7b486>Показать рецепт",
            "item-kind-vanilla" to "обычный",
            "item-kind-custom" to "дополнительный",
            "world-kind-vanilla" to "обычный мир",
            "world-kind-mining" to "мир добычи",
            "world-kind-biomes" to "мир новых биомов",
            "context-outside-privat" to "вне привата",
            "context-empty-hand" to "пустая рука",
            "onboarding-pending" to "есть незавершённый следующий шаг",
            "onboarding-clear" to "новых шагов обучения не видно",
            "requests-short-label" to "<#d7b486>Дела и запросы",
            "requests-tooltip" to "<#e6fff3>Обучение, задания, награды и игровые приглашения.",
            "requests-title" to "<#f4bd6a>Дела и запросы",
            "requests-body" to "<#e6fff3>Обучение: <hint><newline><#969696>Ответы ниже относятся к последнему входящему запросу.<newline>Награды и приглашения проверяются в своих разделах.",
            "check-command-label" to "<#d7b486>Проверить: <label>",
            "check-quests-label" to "<#d7b486>Проверить задания",
            "check-battle-pass-label" to "<#d7b486>Проверить боевой пропуск",
            "check-vote-label" to "<#d7b486>Проверить голосование",
            "check-events-label" to "<#d7b486>Открыть события",
            "check-duels-label" to "<#d7b486>Открыть дуэли",
            "check-privat-label" to "<#d7b486>Проверить приваты",
            "request-tpa-accept-label" to "<#2bba43>Принять телепорт",
            "request-tpa-deny-label" to "<#ff6b61>Отклонить телепорт",
            "request-duel-accept-label" to "<#2bba43>Принять дуэль",
            "request-duel-deny-label" to "<#ff6b61>Отклонить дуэль",
            "search-loading" to "<#e6fff3>Сопоставляю запрос с вашими домами и игроками сети…",
            "problem-cannot-teleport-label" to "<#d7b486>Не телепортирует",
            "problem-cannot-claim-label" to "<#d7b486>Не получается заприватить",
            "problem-cannot-find-player-label" to "<#d7b486>Не вижу игрока",
            "problem-lost-item-label" to "<#d7b486>Не понимаю предмет",
            "problem-command-failed-label" to "<#d7b486>Команда не работает",
            "diagnostic-body" to "<#e6fff3>Что удалось проверить:<newline><#969696><facts><newline><newline><#e6fff3>Выберите ближайший безопасный путь.",
            "fact-homes-ready-yes" to "список домов доступен",
            "fact-homes-ready-no" to "список домов ещё не проверен",
            "fact-husk-ready-yes" to "система телепортации доступна",
            "fact-husk-ready-no" to "система телепортации недоступна",
            "fact-known-world-yes" to "тип текущего мира определён",
            "fact-known-world-no" to "это особый мир",
            "fact-lands-ready-yes" to "система приватов доступна",
            "fact-lands-ready-no" to "система приватов недоступна",
            "fact-outside-land-yes" to "вы сейчас вне чужого привата",
            "fact-outside-land-no" to "вы уже на территории привата",
            "fact-land-owner-yes" to "вы владелец текущего привата",
            "fact-land-owner-no" to "вы не владелец текущего привата",
            "fact-network-list-ready-yes" to "поиск проверяет всю сеть серверов",
            "fact-network-list-ready-no" to "список игроков сети недоступен",
            "fact-held-item-yes" to "предмет находится в основной руке",
            "fact-held-item-no" to "основная рука пустая",
            "fact-server-known-yes" to "текущий сервер определён",
            "fact-server-known-no" to "текущий сервер не определён",
            "my-title" to "<#f4bd6a>Про меня",
            "my-loading" to "<#e6fff3>Собираю ваш профиль…",
            "my-identity" to "<#e6fff3><player><newline><#969696>Сервер: <#e6fff3><server><newline><#969696>Ранг: <#e6fff3><rank>",
            "my-summary" to "<#969696>Баланс: <#e6fff3><balance><newline><#969696>Дома: <#e6fff3><homes>/<max_homes><newline><#969696>Поселения: <#e6fff3><lands>",
            "my-location" to "<#969696>Мир: <#d7b486><world><newline><#969696>Координаты: <#e6fff3><x>, <y>, <z>",
            "my-error" to "<#e6fff3>Часть профиля сейчас недоступна. Быстрые разделы всё равно работают.",
            "my-homes-label" to "<#d7b486>Мои дома",
            "my-homes-tooltip" to "<#e6fff3>Сохранённые точки и перемещения.",
            "my-lands-label" to "<#d7b486>Мои приваты",
            "my-lands-tooltip" to "<#e6fff3>Территория, участники и настройки.",
            "my-rank-label" to "<#d7b486>Мой ранг",
            "my-rank-tooltip" to "<#e6fff3>Текущий ранг и следующие цели.",
            "my-jobs-label" to "<#d7b486>Мои работы",
            "my-jobs-tooltip" to "<#e6fff3>Профессии, уровни и заработок.",
            "my-quests-label" to "<#d7b486>Мои задания",
            "my-quests-tooltip" to "<#e6fff3>Активные задания и награды.",
            "my-skills-label" to "<#d7b486>Мои навыки",
            "my-skills-tooltip" to "<#e6fff3>Открыть навыки и их развитие.",
            "guide-title" to "<#f4bd6a>С чего начать",
            "guide-body" to "<#f4bd6a>1 · Стартовый набор<newline><#e6fff3>Получите первые инструменты и припасы.<newline><newline><#f4bd6a>2 · Выберите мир<newline><#e6fff3>Обычный мир, мир добычи или мир новых биомов.<newline><newline><#f4bd6a>3 · Начните зарабатывать<newline><#e6fff3>Выберите работу и получайте деньги за привычные действия.<newline><newline><#f4bd6a>4 · Дом и поселение<newline><#e6fff3>Сохраните точку дома и защитите территорию поселением.",
            "kit-label" to "<#d7b486>Получить набор",
            "vanilla-label" to "<#d7b486>Обычный мир",
            "mining-label" to "<#d7b486>Мир добычи",
            "biomes-label" to "<#d7b486>Мир новых биомов",
            "jobs-label" to "<#d7b486>Выбрать работу",
            "rules-label" to "<#d7b486>Правила",
            "commands-title" to "<#f4bd6a>Поиск",
            "commands-body" to "<#e6fff3>Опишите, что хотите сделать, обычной фразой.<newline><#969696>Поиск понимает формы слов, близкие значения и небольшие опечатки.",
            "search-input" to "<#fff0d8>Что вы хотите сделать?",
            "search-label" to "<#d7b486>Найти",
            "search-tooltip" to "<#fff0d8>Например: удалить поселение, перенести дом, добавить друга.",
            "search-title" to "<#f4bd6a>Результаты поиска",
            "search-body" to "<#969696>Запрос  <#e6fff3><query><newline><#969696>Найдено  <#e6fff3><count>",
            "search-empty" to "<#fff0d8>Не понял запрос. Опишите действие и объект: «перенести дом» или «добавить игрока».",
            "search-result-tooltip" to "<#fff0d8><description><newline><#8d7768>Открыть нужный раздел",
            "category-start-label" to "<#d7b486>Начало игры",
            "category-travel-label" to "<#d7b486>Телепортация",
            "category-protection-label" to "<#d7b486>Защита",
            "category-trade-label" to "<italic:false><#f4d87a>Торговля ›",
            "category-progress-label" to "<italic:false><#c4abff>Развитие ›",
            "category-social-label" to "<#d7b486>Общение и сервер",
            "category-activities-label" to "<italic:false><#ffb277>Активности ›",
            "category-technology-label" to "<italic:false><#85dfc4>Технологии ›",
            "category-settings-label" to "<#aaa49a>Настройки ›",
            "category-activities-tooltip" to "<#e6fff3>События, дуэли, данжи и фермы.",
            "category-technology-tooltip" to "<#e6fff3>Предметы, зачарования, механизмы и транспорт.",
            "category-settings-tooltip" to "<#e6fff3>Личные настройки игры и интерфейса.<newline><#969696>Чат, тропинки, полёт, порталы и управление.<newline>В названии кнопки — текущий режим,<newline>в подсказке — его назначение.",
            "category-trade-tooltip" to "<#e6fff3>Магазины, быстрая продажа и аукцион.",
            "category-progress-tooltip" to "<#e6fff3>Ранг, работы, задания и навыки.",
            "category-social-tooltip" to "<#e6fff3>Голосование и выбор режима чата.",
            "category-start-title" to "<#f4bd6a>Начало игры",
            "category-travel-title" to "<#f4bd6a>Телепортация",
            "category-protection-title" to "<#f4bd6a>Защита",
            "category-trade-title" to "<#f4bd6a>Торговля",
            "category-progress-title" to "<#f4bd6a>Развитие",
            "category-social-title" to "<#f4bd6a>Общение и сервер",
            "category-activities-title" to "<#f4bd6a>Активности",
            "category-technology-title" to "<#f4bd6a>Технологии",
            "category-settings-title" to "<italic:false><#835326>Настройки",
            "setting-chat-current" to "<#d7b486>Канал чата: <state>",
            "setting-particles-current" to "<#d7b486>Частицы: <state>",
            "setting-trails-current" to "<#d7b486>Тропинки: <state>",
            "chat-global-state" to "глобальный",
            "chat-local-state" to "локальный",
            "legacy-settings-scoreboard" to "<#d7b486>Панель: <state><#d7b486> ›",
            "legacy-settings-scoreboard-tooltip" to "<#e6fff3>Панель с информацией справа на экране.<newline><#969696>Выберите подходящий набор данных:<newline>баланс, координаты, профессии или прогресс.<newline><newline><#d7b486>Нажмите, чтобы выбрать один из 20 видов<newline>или полностью скрыть панель.",
            "legacy-settings-tablist" to "<#d7b486>Tab: <state><#d7b486> ›",
            "legacy-settings-tablist-tooltip" to "<#e6fff3>Оформление списка игроков по клавише Tab.<newline><#969696>Виды отличаются набором дополнительных<newline>данных: профиль, баланс, место и прогресс.<newline><newline><#d7b486>Нажмите, чтобы выбрать один из 20 видов<newline>или выключить дополнительное оформление.",
            "legacy-settings-lands" to "<#d7b486>Границы земель ›",
            "legacy-settings-lands-tooltip" to "<#e6fff3>Подсветка границ территории Lands.<newline><#969696>Помогает понять, где заканчивается участок<newline>и какие блоки входят в поселение.<newline><newline><#d7b486>Нажмите, чтобы показать границы рядом<newline>или убрать их отображение.",
            "legacy-settings-portal-by-other" to "<#d7b486>Чужие порталы: <state>",
            "legacy-settings-portal-for-other" to "<#d7b486>Мои порталы для гостей: <state>",
            "legacy-settings-portal-tooltip" to "<#969696>Разрешить телепортацию через порталы игроков.",
            "legacy-settings-notifications" to "<#d7b486>Уведомления: <state>",
            "legacy-settings-notifications-tooltip" to "<#e6fff3>Системные объявления RusCrafting в чате.<newline><#969696>Отключите их, если хотите меньше<newline>информационных сообщений от сервера.<newline>Это отдельная настройка от режима чата.<newline><newline><#d7b486>Нажмите, чтобы включить или выключить.",
            "legacy-settings-flight" to "<#d7b486>Полёт и подзарядка ›",
            "legacy-settings-flight-tooltip" to "<#e6fff3>Полёт с расходуемым запасом заряда.<newline><#969696>Заряд тратится при перемещении и зависании.<newline>Его можно пополнять за опыт или игровые деньги.<newline><newline><#d7b486>Нажмите, чтобы узнать правила расхода,<newline>выбрать автопополнение и управлять полётом.",
            "legacy-settings-shift-edit" to "<#d7b486>Правка табличек: <state>",
            "legacy-settings-shift-tooltip" to "<#e6fff3>Редактирование текста уже поставленных табличек.<newline><#969696>Нажмите ПКМ по доступной для правки табличке;<newline>при необходимости удерживайте Shift.<newline>Защита территории продолжает действовать.<newline><newline><#d7b486>Нажмите, чтобы переключить редактирование.",
            "legacy-settings-resource-pack" to "<#d7b486>Ресурспак: <state>",
            "legacy-settings-resource-pack-tooltip" to "<#e6fff3>Автоматическая загрузка ресурспака при входе.<newline><#969696>Он добавляет серверные модели, предметы<newline>и значки, которые используются в меню.<newline>Выбор будет учитываться при следующем входе.<newline><newline><#d7b486>Нажмите, чтобы включить или выключить.",
            "legacy-settings-totem" to "<#d7b486>Полоса автототема: <state>",
            "legacy-settings-totem-tooltip" to "<#e6fff3>Полоса состояния автототема вверху экрана.<newline><#969696>Показывает его перезарядку, когда работает<newline>механика автоматического использования тотема.<newline>Настройка управляет отображением полосы.<newline><newline><#d7b486>Нажмите, чтобы показать или скрыть её.",
            "legacy-settings-stairs-sit" to "<#d7b486>Сидеть на ступеньках: <state>",
            "legacy-settings-stairs-tooltip" to "<#e6fff3>Посадка на ступеньки по правой кнопке мыши.<newline><#969696>Включите, чтобы использовать их как сиденье.<newline>Отключите, если случайно садитесь при стройке.<newline><newline><#d7b486>Нажмите, чтобы включить или выключить.",
            "legacy-settings-tpa" to "<#d7b486>Запросы телепортации: <state>",
            "legacy-settings-tpa-tooltip" to "<#e6fff3>Входящие запросы на телепортацию от игроков.<newline><#969696>Включено — вы можете получать запросы /tpa.<newline>Выключено — запросы будут игнорироваться.<newline>Разрешение запроса не означает его принятие.<newline><newline><#d7b486>Нажмите, чтобы переключить приём запросов.",
            "legacy-settings-portal-style" to "<#d7b486>Вид портала: <state><#d7b486> ›",
            "legacy-settings-portal-style-tooltip" to "<#e8dfd2>Внешний вид создаваемого вами портала.<newline><#aaa49a>Можно выбрать обычное, астральное, солнечное<newline>и другие оформления. Текущий вид указан на кнопке.<newline><newline><#d7b486>Нажмите, чтобы открыть выбор оформления.",
            "legacy-settings-admin" to "<#d7b486>Админские настройки: <#e6fff3><state>",
            "legacy-settings-admin-tooltip" to "<#e6fff3>Личные служебные режимы администратора.<newline><#969696>Откроется отдельное меню со Spy, CSpy<newline>и другими доступными настройками.<newline><newline><#d7b486>Нажмите, чтобы открыть меню.",
            "legacy-state-on" to "<#9bd48d>✔ вкл.",
            "legacy-state-off" to "<#aaa49a>○ выкл.",
            "legacy-state-exp" to "за опыт",
            "legacy-state-money" to "за деньги",
            "legacy-state-unknown" to "<#dfa754>? неизвестно",
            "legacy-state-available" to "доступно",
            "legacy-state-locked" to "недоступно",
            "legacy-state-style" to "вид",
            "legacy-state-origin" to "Обычный Origin",
            "legacy-state-legacy" to "Классический ARC",
            "legacy-state-astral" to "Астральный",
            "legacy-state-chaos" to "Хаос",
            "legacy-state-solar" to "Солнечный",
            "legacy-state-void" to "Пустота",
            "legacy-options-body" to "<#969696>Выберите параметр. Текущий режим указан в заголовке.",
            "legacy-mode-label" to "<#d7b486>Вид <number>",
            "legacy-action-scoreboard-off" to "<#969696>Выключить панель",
            "legacy-action-tablist-off" to "<#969696>Выключить список",
            "legacy-action-lands-show" to "<#d7b486>Показать границы",
            "legacy-action-lands-hide" to "<#969696>Скрыть границы",
            "legacy-action-flight-exp" to "<#d7b486>За очки опыта",
            "legacy-action-flight-money" to "<#d7b486>За игровые деньги",
            "legacy-action-flight-off" to "<#aaa49a>Отключить",
            "legacy-action-flight-recharge" to "<italic:false><#d7b486>Пополнить заряд ›",
            "legacy-action-flight-toggle" to "<#d7b486>Переключить полёт",
            "legacy-settings-scoreboard-mode-1" to "<#d7b486>Дефолт",
            "legacy-settings-scoreboard-mode-2" to "<#d7b486>Мини",
            "legacy-settings-scoreboard-mode-3" to "<#d7b486>Кошелёк",
            "legacy-settings-scoreboard-mode-4" to "<#d7b486>Профиль",
            "legacy-settings-scoreboard-mode-5" to "<#d7b486>Земли",
            "legacy-settings-scoreboard-mode-6" to "<#d7b486>Координаты",
            "legacy-settings-scoreboard-mode-7" to "<#d7b486>Онлайн",
            "legacy-settings-scoreboard-mode-8" to "<#d7b486>Сервер",
            "legacy-settings-scoreboard-mode-9" to "<#d7b486>Время",
            "legacy-settings-scoreboard-mode-10" to "<#d7b486>Профессии",
            "legacy-settings-scoreboard-mode-11" to "<#d7b486>Навыки",
            "legacy-settings-scoreboard-mode-12" to "<#d7b486>Добыча",
            "legacy-settings-scoreboard-mode-13" to "<#d7b486>Строитель",
            "legacy-settings-scoreboard-mode-14" to "<#d7b486>Исследователь",
            "legacy-settings-scoreboard-mode-15" to "<#d7b486>Охотник",
            "legacy-settings-scoreboard-mode-16" to "<#d7b486>Быт",
            "legacy-settings-scoreboard-mode-17" to "<#d7b486>Баланс",
            "legacy-settings-scoreboard-mode-18" to "<#d7b486>Сводка",
            "legacy-settings-scoreboard-mode-19" to "<#d7b486>Лайт",
            "legacy-settings-scoreboard-mode-20" to "<#d7b486>Админ",
            "legacy-settings-tablist-mode-1" to "<#d7b486>Дефолт",
            "legacy-settings-tablist-mode-2" to "<#d7b486>Мини",
            "legacy-settings-tablist-mode-3" to "<#d7b486>Импульс",
            "legacy-settings-tablist-mode-4" to "<#d7b486>Профиль",
            "legacy-settings-tablist-mode-5" to "<#d7b486>Кошелёк",
            "legacy-settings-tablist-mode-6" to "<#d7b486>Место",
            "legacy-settings-tablist-mode-7" to "<#d7b486>Координаты",
            "legacy-settings-tablist-mode-8" to "<#d7b486>Сервер",
            "legacy-settings-tablist-mode-9" to "<#d7b486>Закат",
            "legacy-settings-tablist-mode-10" to "<#d7b486>Прогресс",
            "legacy-settings-tablist-mode-11" to "<#d7b486>Профессии",
            "legacy-settings-tablist-mode-12" to "<#d7b486>Навыки",
            "legacy-settings-tablist-mode-13" to "<#d7b486>Сеть",
            "legacy-settings-tablist-mode-14" to "<#d7b486>Навигация",
            "legacy-settings-tablist-mode-15" to "<#d7b486>Сессия",
            "legacy-settings-tablist-mode-16" to "<#d7b486>Спектр",
            "legacy-settings-tablist-mode-17" to "<#d7b486>Сводка",
            "legacy-settings-tablist-mode-18" to "<#d7b486>Связь",
            "legacy-settings-tablist-mode-19" to "<#d7b486>Лайт",
            "legacy-settings-tablist-mode-20" to "<#d7b486>Админ",
            "settings-body" to "<#969696>Чат: <#e6fff3><chat><newline><#969696>Тропинки: <#e6fff3><trails><newline><newline><#969696>Текущий режим — в названии кнопки.<newline>Наведите на неё, чтобы узнать подробности.",
            "state-on" to "включено",
            "state-off" to "выключено",
            "state-unknown" to "выберите состояние",
            "players-title" to "<#f4bd6a>Игроки",
            "players-body" to "<#e6fff3>Игроки: <#e6fff3><total><newline><#969696>Где ищем: <#e6fff3><scope><newline><#969696>Страница <page>/<pages> · на экране <count>",
            "players-empty" to "<#969696>Игроков по этому фильтру нет.<newline>Измените ник или переключитесь на всю сеть.",
            "players-input" to "<#e6fff3>Ник игрока",
            "players-search-label" to "<#d7b486>Найти игрока",
            "players-search-tooltip" to "<#969696>Применить фильтр",
            "player-label" to "<#d7b486><player>",
            "player-tooltip" to "<#969696>Сервер: <#d7b486><server>",
            "player-server-unknown" to "неизвестен",
            "player-title" to "<#f4bd6a><player>",
            "player-body" to "<#e6fff3><player><newline><#969696>Сейчас на сервере <#e6fff3><server><#969696>.<newline><newline><#e6fff3>Выберите действие.",
            "player-tpa-label" to "<#d7b486>Телепортироваться к нему",
            "player-tpahere-label" to "<#d7b486>Позвать к себе",
            "player-message-label" to "<#d7b486>Написать сообщение",
            "player-pay-label" to "<#d7b486>Перевести деньги",
            "player-duel-label" to "<#d7b486>Вызвать на дуэль",
            "player-invite-label" to "<#d7b486>Пригласить в поселение",
            "message-title" to "<#f4bd6a>Сообщение · <player>",
            "message-body" to "<#e6fff3>Напишите короткое личное сообщение для <#e6fff3><player><#e6fff3>.",
            "message-input" to "<#e6fff3>Текст сообщения",
            "message-send-label" to "<#2bba43>Отправить",
            "invalid-message" to "<#ff6b61>Сообщение должно занимать от 1 до 128 символов и быть в одну строку.",
            "pay-title" to "<#f4bd6a>Перевод · <player>",
            "pay-body" to "<#e6fff3>Укажите сумму. Перед переводом будет подтверждение.",
            "pay-input" to "<#e6fff3>Сумма",
            "pay-continue-label" to "<#d7b486>Проверить перевод",
            "pay-confirm-title" to "<#f4bd6a>Подтверждение перевода",
            "pay-confirm-body" to "<#e6fff3>Перевести <#e6fff3><amount> <#e6fff3>игроку <#e6fff3><player><#e6fff3>?",
            "pay-confirm-label" to "<#2bba43>Подтвердить перевод",
            "invalid-amount" to "<#ff6b61>Введите положительную сумму, не больше двух знаков после запятой.",
            "recovery-label" to "<#d7b486>Что случилось?",
            "recovery-tooltip" to "<#e6fff3>Быстрые выходы, если вы застряли или потерялись.",
            "recovery-title" to "<#f4bd6a>Что случилось?",
            "recovery-body" to "<#e6fff3>Выберите самое похожее действие.<newline><#969696>Если не помогло — откройте поиск и опишите проблему своими словами.",
            "category-body" to "<#e6fff3>Выберите действие. Подробности — при наведении.<newline><#969696>После закрытия игрового инвентаря вы вернётесь сюда.",
            "command-label" to "<#d7b486><label>",
            "command-vote-label" to "<#d7b486>Голосование",
            "command-chat-global-label" to "<#d7b486>Глобальный чат",
            "command-chat-local-label" to "<#d7b486>Локальный чат",
            "command-lands-borders-label" to "<#d7b486>Границы привата",
            "command-trails-on-label" to "<#d7b486>Протаптывать тропинки",
            "command-trails-off-label" to "<#d7b486>Не протаптывать тропинки",
            "command-particles-label" to "<#d7b486>Частицы",
            "command-tpa-ignore-label" to "<#d7b486>Запросы телепорта",
            "command-tooltip" to "<#fff0d8><description><newline><#8d7768>/<command>",
            "travel-title" to "<#f4bd6a>Телепортация",
            "travel-loading" to "<#fff0d8>Загружаю ваши дома…",
            "travel-body" to "<#8d7768>Дома: <#e6fff3><homes>/<max_homes><newline><#fff0d8>Выберите дом или другое направление.",
            "travel-empty" to "<#fff0d8>У вас пока нет домов. Создайте первый в текущей точке.",
            "travel-limit" to "<#8d7768>Свободных слотов нет. Удалите или перенесите существующий дом.",
            "travel-error" to "<#fff0d8>Дома сейчас не загрузились, но остальные способы телепортации доступны.",
            "home-label" to "<#d7b486><home>",
            "home-tooltip" to "<#fff0d8><server> · <world><newline><#8d7768><x>, <y>, <z>",
            "create-home-label" to "<#d7b486>Новый дом",
            "create-home-tooltip" to "<#fff0d8>Сохранить текущую точку.",
            "home-create-title" to "<#f4bd6a>Новый дом",
            "home-create-body" to "<#fff0d8>Введите короткое имя без пробелов.<newline><#8d7768>Дом будет создан в вашей текущей точке.",
            "home-name-input" to "<#fff0d8>Название дома",
            "home-create-submit" to "<#2bba43>Создать",
            "home-title" to "<#f4bd6a>Дом · <home>",
            "home-body" to "<#8d7768>Сервер: <#fff0d8><server><newline><#8d7768>Мир: <#fff0d8><world><newline><#8d7768>Координаты: <#fff0d8><x>, <y>, <z>",
            "home-teleport-label" to "<#d7b486>Телепортироваться",
            "home-teleport-tooltip" to "<#fff0d8>Переместиться в сохранённую точку.",
            "home-relocate-label" to "<#d7b486>Перенести сюда",
            "home-relocate-tooltip" to "<#fff0d8>Заменить точку вашим текущим положением. Потребуется подтверждение.",
            "home-delete-label" to "<#ff6b61><bold>Удалить дом",
            "home-delete-tooltip" to "<#fff0d8>Удалить сохранённую точку. Потребуется подтверждение.",
            "home-relocate-title" to "<#f4bd6a>Перенести · <home>",
            "home-relocate-body" to "<#fff0d8>Заменить сохранённую точку дома <#e6fff3><home> <#fff0d8>вашим текущим положением?",
            "home-relocate-confirm" to "<#2bba43>Перенести точку",
            "home-delete-title" to "<#ff6b61>Удаление · <home>",
            "home-delete-body" to "<#c42323><bold>Это необратимое действие.<newline><#fff0d8>Дом <#e6fff3><home> <#fff0d8>будет удалён.",
            "home-delete-confirm" to "<#ff6b61><bold>Удалить навсегда",
            "warps-label" to "<#d7b486>Варпы игроков",
            "spawn-label" to "<#d7b486>Спавн",
            "rtp-label" to "<#d7b486>Случайное место",
            "back-command-label" to "<#d7b486>На прежнее место",
            "stuck-label" to "<#d7b486>Выбраться на спавн",
            "public-homes-label" to "<#d7b486>Публичные дома",
            "public-homes-tooltip" to "<#fff0d8>Посмотреть открытые дома игроков.",
            "invalid-home" to "<#c42323>Имя дома: до 32 букв, цифр, _ или - без пробелов.",
            "action-failed" to "<#c42323>Команда не выполнилась. Попробуйте ещё раз или сообщите администрации.",
        )

        internal val COMMANDS = linkedMapOf(
            "menu" to HelpCenterCommandText("Главное меню", "Все игровые разделы", "разделы сервер mm"),
            "kit" to HelpCenterCommandText("Набор новичка", "Получить стартовые предметы", "старт начало вещи"),
            "rules" to HelpCenterCommandText("Правила", "Правила игрового сервера", "запрещено можно"),
            "tutorial" to HelpCenterCommandText("Обучение", "Вернуться к обучению", "гайд начало"),
            "warps" to HelpCenterCommandText("Варпы игроков", "Публичные точки игроков", "телепорт точки"),
            "spawn" to HelpCenterCommandText("Спавн", "Вернуться на спавн", "телепорт начало"),
            "rtp" to HelpCenterCommandText("Случайное место", "Телепорт в случайную безопасную точку", "рандом ресурсы"),
            "back" to HelpCenterCommandText("Вернуться назад", "Вернуться к прошлой позиции", "телепорт смерть"),
            "stuck" to HelpCenterCommandText("Выбраться на спавн", "Аварийный возврат со сложного места", "застрял помощь"),
            "vanilla" to HelpCenterCommandText("Обычный мир", "Перейти в обычный мир выживания", "ванильный стандартный мир ресурсы база"),
            "mining" to HelpCenterCommandText("Мир добычи", "Перейти в обновляемый ресурсный мир", "шахта ресурсы"),
            "biomes" to HelpCenterCommandText("Мир новых биомов", "Перейти в мир выживания с новыми биомами", "новые биомы необычный мир база"),
            "privat" to HelpCenterCommandText("Приват", "Создание и защита территории", "земля поселение lands приват защита"),
            "events" to HelpCenterCommandText("События", "Активные серверные события", "ивенты события награды"),
            "duels" to HelpCenterCommandText("Дуэли", "Сразиться с другим игроком", "пвп бой поединок"),
            "battle-pass" to HelpCenterCommandText("Боевой пропуск", "Задания и награды сезона", "бп сезон пропуск награды"),
            "giveaways" to HelpCenterCommandText("Розыгрыши", "Активные розыгрыши сервера", "giveaway конкурс приз"),
            "dungeons" to HelpCenterCommandText("Данжи", "Меню данжей и боссов", "данж подземелье боссы элитные мобы"),
            "farms" to HelpCenterCommandText("Фермы", "Управление игровыми фермами", "ферма урожай животные"),
            "shops" to HelpCenterCommandText("Магазины", "Магазины игроков и сервера", "рынок купить продать"),
            "sell" to HelpCenterCommandText("Быстрая продажа", "Продать подходящие предметы", "деньги рынок"),
            "auction" to HelpCenterCommandText("Аукцион", "Торговля предметами между игроками", "ah рынок купить продать"),
            "bank" to HelpCenterCommandText("Банк", "Открыть личный банковский счёт", "деньги счет вклад"),
            "investments" to HelpCenterCommandText("Инвестиции", "Портфель и рынок акций", "акции биржа портфель"),
            "rank" to HelpCenterCommandText("Ранги", "Текущий ранг и следующие цели", "уровень развитие"),
            "rankup" to HelpCenterCommandText("Повысить ранг", "Проверить требования повышения", "уровень развитие"),
            "jobs" to HelpCenterCommandText("Работы", "Профессии и заработок", "деньги профессия"),
            "quests" to HelpCenterCommandText("Задания", "Активные задания и награды", "квест развитие"),
            "skills" to HelpCenterCommandText("Навыки", "Навыки и их развитие", "auraskills способности развитие"),
            "slimefun" to HelpCenterCommandText("Книга технологий", "Открыть справочник Slimefun", "slimefun сф механизмы рецепты"),
            "items" to HelpCenterCommandText("Новые предметы", "Каталог дополнительных предметов", "itemsadder предметы рецепты"),
            "enchants" to HelpCenterCommandText("Зачарования", "Список особых зачарований", "энчанты чары магия"),
            "enchanter" to HelpCenterCommandText("Зачарователь", "Магазин особых зачарований", "купить чары энчанты"),
            "builder" to HelpCenterCommandText("Инструменты строителя", "Получить книгу инструментов", "стройка билдер блоки"),
            "mounts" to HelpCenterCommandText("Транспорт", "Коллекция ездовых существ", "маунты транспорт питомцы"),
            "lands-borders" to HelpCenterCommandText("Границы поселения", "Показать границы участка", "чанки границы приват"),
            "trails-on" to HelpCenterCommandText("Протаптывать тропинки", "Создавать тропинки частой ходьбой по земле", "trails тропа тропинки дорожки земля ходьба"),
            "trails-off" to HelpCenterCommandText("Не протаптывать тропинки", "Отключить создание тропинок от своих шагов", "trails тропа тропинки дорожки земля ходьба"),
            "particles" to HelpCenterCommandText("Частицы", "Включить или выключить личные частицы", "эффекты партиклы"),
            "tpa-ignore" to HelpCenterCommandText("Запросы телепорта", "Включить или выключить входящие запросы", "tpa запросы игнор"),
            "vote" to HelpCenterCommandText(
                "Голосование",
                "Открыть ссылки для голосования за сервер",
                "vote votes голос голосование рейтинг награда мониторинг",
            ),
            "chat-global" to HelpCenterCommandText(
                "Глобальный чат",
                "Переключить режим на глобальный чат",
                "чат глобальный общий g всем писать",
            ),
            "chat-local" to HelpCenterCommandText(
                "Локальный чат",
                "Переключить режим на локальный чат рядом",
                "чат локальный рядом l местный писать",
            ),
        )

        internal val INTENTS = linkedMapOf(
            "context" to HelpCenterIntentText("Что рядом со мной", "Мир, координаты и текущий приват.", "рядом местоположение координаты текущий мир"),
            "requests" to HelpCenterIntentText("Входящие запросы", "Ответы на запросы и проверка наград.", "входящие запросы принять отклонить награды приглашения"),
            "held-item" to HelpCenterIntentText("Предмет в руке", "Рецепт, каталог и торговля.", "предмет в руке рецепт что это назначение"),
            "goals" to HelpCenterIntentText("Чем заняться", "Подбор занятий по вашей цели.", "чем заняться скучно заработать строить исследовать играть вместе"),
            "favorites" to HelpCenterIntentText("Избранное", "Закреплённые и последние действия.", "избранное недавнее закрепить быстрый доступ любимое"),
            "my" to HelpCenterIntentText(
                "Про меня",
                "Открыть личный профиль, дома, земли и прогресс",
                "мой профиль баланс деньги координаты где я мои данные",
            ),
            "player-find" to HelpCenterIntentText(
                "Найти игрока",
                "Открыть действия с игроками онлайн на всей сети",
                "игрок друг написать другу личка лс msg телепорт сообщение перевод дуэль пригласить",
            ),
            "recovery" to HelpCenterIntentText(
                "Что случилось?",
                "Быстрые действия, если вы застряли или потерялись",
                "застрял потерялся умер не работает проблема помощь",
            ),
            "home-create" to HelpCenterIntentText(
                "Создать дом",
                "Сохранить текущую точку как новый дом",
                "поставить дом создать хом sethome сохранить точку",
            ),
            "home-move" to HelpCenterIntentText(
                "Перенести дом",
                "Выбрать дом и заменить его сохранённую точку",
                "передвинуть переместить перенести точку дома edithome",
            ),
            "home-delete" to HelpCenterIntentText(
                "Удалить дом",
                "Выбрать сохранённый дом для удаления",
                "удалить стереть снести дом хом delhome",
            ),
            "land-create" to HelpCenterIntentText(
                "Создать поселение",
                "Открыть приват и создать новое поселение",
                "создать основать сделать поселение землю приват",
            ),
            "land-delete" to HelpCenterIntentText(
                "Удалить поселение",
                "Открыть приват и выбрать поселение для удаления",
                "как удалить распустить закрыть снести поселение землю приват lands",
            ),
            "land-invite" to HelpCenterIntentText(
                "Добавить игрока в поселение",
                "Выбрать поселение и пригласить участника",
                "добавить пригласить позвать друга игрока участника доверить trust",
            ),
            "land-remove" to HelpCenterIntentText(
                "Исключить игрока из поселения",
                "Выбрать поселение и убрать участника",
                "удалить выгнать исключить убрать игрока участника untrust",
            ),
            "land-main-block" to HelpCenterIntentText(
                "Перенести блок поселения",
                "Открыть управление главным блоком поселения",
                "перенести передвинуть переместить блок колокол костер mainblock",
            ),
            "land-claim" to HelpCenterIntentText(
                "Расширить территорию",
                "Открыть приват и управление участками",
                "заприватить занять добавить чанк участок территорию claim",
            ),
        )
    }
}
