package ru.arc.helpcenter

import ru.arc.config.Config
import ru.arc.config.ConfigManager
import java.nio.file.Path

data class HelpCenterCommandText(
    val label: String,
    val description: String,
    val keywords: String,
)

data class HelpCenterIntentText(
    val label: String,
    val description: String,
    val keywords: String,
)

data class HelpCenterSettings(
    val enabled: Boolean,
    val maxHomes: Int,
    val maxSearchResults: Int,
    val loadTimeoutSeconds: Long,
    private val text: Map<String, String>,
    private val commands: Map<String, HelpCenterCommandText>,
    private val intents: Map<String, HelpCenterIntentText>,
) {
    fun text(key: String): String = text.getValue(key)

    fun command(id: String): HelpCenterCommandText = commands.getValue(id)

    fun intent(id: String): HelpCenterIntentText = intents.getValue(id)
}

class HelpCenterConfig(private val config: Config) {
    fun snapshot(): HelpCenterSettings {
        val maxHomes = config.integer("limits.max-homes", 12)
        val maxSearchResults = config.integer("limits.max-search-results", 8)
        val loadTimeoutSeconds = config.long("limits.load-timeout-seconds", 3)
        require(maxHomes in 1..32) { "Help center max-homes must be in 1..32" }
        require(maxSearchResults in 1..32) { "Help center max-search-results must be in 1..32" }
        require(loadTimeoutSeconds in 1..10) { "Help center load-timeout-seconds must be in 1..10" }
        return HelpCenterSettings(
            enabled = config.bool("enabled", true),
            maxHomes = maxHomes,
            maxSearchResults = maxSearchResults,
            loadTimeoutSeconds = loadTimeoutSeconds,
            text = DEFAULT_TEXT.mapValues { (key, fallback) -> required("text.$key", fallback) },
            commands = COMMANDS.mapValues { (id, fallback) ->
                HelpCenterCommandText(
                    label = required("commands.$id.label", fallback.label),
                    description = required("commands.$id.description", fallback.description),
                    keywords = required("commands.$id.keywords", fallback.keywords),
                )
            },
            intents = INTENTS.mapValues { (id, fallback) ->
                HelpCenterIntentText(
                    label = required("intents.$id.label", fallback.label),
                    description = required("intents.$id.description", fallback.description),
                    keywords = required("intents.$id.keywords", fallback.keywords),
                )
            },
        )
    }

    private fun required(path: String, fallback: String): String = config.string(path, fallback).also { value ->
        require(value.isNotBlank()) { "Help center value '$path' cannot be blank" }
        require(value.length <= 2_000) { "Help center value '$path' is too long" }
    }

    companion object {
        private const val RESOURCE = "help-center.yml"

        fun load(dataPath: Path): HelpCenterConfig {
            val source = ConfigManager.ofModule(dataPath, RESOURCE)
            source.mergeMissingFromBundled("modules/$RESOURCE")
            return HelpCenterConfig(source)
        }

        private val DEFAULT_TEXT = linkedMapOf(
            "category-empty" to "<#969696>В этом разделе пока нет доступных действий.<newline>Попробуйте поиск или другой раздел.",
            "diagnostic-command-failed-help" to "<#e6fff3>Найдите действие через поиск — там есть описание и точная команда.<newline>Проверьте последнее сообщение чата: в нём может быть причина отказа.<newline><#969696>Недоступный на этом сервере раздел может отсутствовать в каталоге.",
            "diagnostic-lost-item-help" to "<#e6fff3>Возьмите предмет в основную руку и откройте его карточку.<newline>Для дополнительных предметов доступен рецепт, если его предоставляет каталог.<newline><#969696>Переход в магазин или на аукцион сам по себе ничего не продаёт.",
            "diagnostic-cannot-find-player-help" to "<#e6fff3>Откройте «Игроки», выберите всю сеть и сбросьте поиск.<newline>Попробуйте часть ника, затем обновите список.<newline><#969696>В списке показаны только игроки онлайн.",
            "diagnostic-cannot-claim-help" to "<#e6fff3>Выберите своё поселение в разделе «Приват».<newline>Проверьте лимит чанков, доступный баланс и права на расширение.<newline><#969696>Чужую территорию занять нельзя. Подробный отказ покажет Lands.",
            "diagnostic-cannot-teleport-help" to "<#e6fff3>Не двигайтесь во время отсчёта телепортации.<newline>Проверьте сохранённые дома или отправьте другу новый запрос.<newline><#969696>Если команда отказала, причина будет в последнем сообщении чата.",
            "goal-together-body" to "<#e6fff3>Найдите друга в сети: можно написать, позвать к себе или пригласить в приват.<newline><#969696>События и дуэли помогут выбрать совместное занятие.",
            "goal-develop-body" to "<#e6fff3>Откройте ранг, чтобы увидеть условия следующего повышения.<newline><#969696>Работы, задания и навыки дают отдельные цели для развития.",
            "goal-fight-body" to "<#e6fff3>Дуэли — для боя с игроком, данжи — для приключений с противниками.<newline><#969696>Условия участия и награды показаны внутри выбранной активности.",
            "goal-explore-body" to "<#e6fff3>Выберите мир или готовую точку для путешествия.<newline><#969696>Перед дальней дорогой сохраните дом в разделе «Телепортация».",
            "goal-build-body" to "<#e6fff3>Сначала защитите место для базы, затем выбирайте материалы и инструменты.<newline><#969696>В технологиях есть механизмы, а в каталоге — дополнительные предметы.",
            "goal-earn-body" to "<#e6fff3>Работы платят за игровые действия, а магазины выкупают ресурсы.<newline><#969696>Редкие вещи можно предложить другим игрокам на аукционе.",
            "favorites-picker-body" to "<#e6fff3>Выберите раздел, затем нужное действие.<newline><#969696>В его карточке нажмите «Добавить в избранное».",
            "favorites-picker-title" to "<#f4bd6a>Добавить в избранное",
            "favorites-full" to "<#f4bd6a>Все четыре места заняты.<newline><#e6fff3>Уберите ненужное действие в избранном, чтобы закрепить новое.",
            "action-unavailable" to "<#ff6b61>Действие сейчас недоступно. Откройте раздел заново.",
            "page-next-label" to "<#92bed8>Следующая →",
            "page-previous-label" to "<#92bed8>← Предыдущая",
            "refresh-tooltip" to "<#e6fff3>Загрузить актуальный список, сохранив фильтр.",
            "refresh-label" to "<#92bed8>Обновить",
            "players-clear-label" to "<#92bed8>Сбросить поиск",
            "players-local-label" to "<#92bed8>Только мой сервер",
            "players-network-label" to "<#92bed8>Вся сеть",
            "players-all-servers" to "вся сеть",
            "root-title" to "<#f4bd6a>Главное меню",
            "root-body" to "<#e6fff3>Выберите раздел или найдите действие по смыслу.<newline><#969696>Дома, друзья и игровые возможности — в одном месте.",
            "now-label" to "<#f4bd6a>Про меня",
            "now-tooltip" to "<#e6fff3>Ваше состояние и полезные следующие шаги.",
            "players-label" to "<#92bed8>Игроки",
            "players-tooltip" to "<#e6fff3>Телепорт, сообщение, перевод, дуэль или приглашение.",
            "my-label" to "<#92bed8>Про меня",
            "my-tooltip" to "<#e6fff3>Ваш профиль, дома, поселения и прогресс.",
            "guide-label" to "<#f4bd6a>С чего начать",
            "guide-tooltip" to "<#e6fff3>Первые шаги без лишних команд.",
            "commands-label" to "<#92bed8>Поиск",
            "commands-tooltip" to "<#e6fff3>Найти действие обычной фразой.",
            "travel-label" to "<#92bed8>Телепортация",
            "travel-tooltip" to "<#e6fff3>Дома, миры, варпы и возврат.",
            "privat-label" to "<#92bed8>Приват",
            "privat-tooltip" to "<#e6fff3>Создание, территория, участники и подробный гайд.",
            "main-menu-label" to "<#969696>Главное меню",
            "main-menu-tooltip" to "<#e6fff3>Открыть остальные игровые разделы сервера.",
            "back-label" to "<#969696>Назад",
            "root-label" to "<#969696>К разделам",
            "not-available" to "—",
            "now-title" to "<#f4bd6a>Про меня",
            "now-identity" to "<#f4bd6a><player><newline><#969696>Сервер: <#e6fff3><server> <#969696>· Онлайн: <#e6fff3><online>",
            "now-progress" to "<#969696>Ранг: <#e6fff3><rank><newline><#969696>Баланс: <#f4bd6a><balance><newline><#969696>Дома: <#e6fff3><homes>/<max_homes> <#969696>· Приваты: <#e6fff3><lands>",
            "now-location" to "<#969696>Мир: <#e6fff3><world><newline><#969696>Координаты: <#e6fff3><x>, <y>, <z><newline><#969696>Чат: <#e6fff3><chat>",
            "rec-home-label" to "<#f4bd6a>Поставить первый дом",
            "rec-land-label" to "<#2bba43>Защитить территорию",
            "rec-rank-label" to "<#2bba43>Следующая цель ранга",
            "rec-bp-label" to "<#f4bd6a>Боевой пропуск",
            "rec-events-label" to "<#f4bd6a>Текущие события",
            "favorites-short-label" to "<#92bed8>Избранное и недавнее",
            "favorites-tooltip" to "<#e6fff3>Закреплённые и последние действия.",
            "favorites-title" to "<#92bed8>Избранное и недавнее",
            "personalization-loading" to "<#e6fff3>Загружаю ваши действия…",
            "personalization-unavailable" to "<#f4bd6a>Избранное сейчас недоступно, но остальные разделы работают.",
            "favorites-body" to "<#e6fff3>Избранное: <#f4bd6a><favorites>/4<newline><#969696>★ — закреплено · ↻ — недавно использовано<newline>Выберите действие, чтобы открыть его или убрать из избранного.",
            "favorite-command-label" to "<#f4bd6a>★ <label>",
            "recent-command-label" to "<#92bed8>↻ <label>",
            "favorite-find-label" to "<#92bed8>Выбрать из каталога",
            "action-title" to "<#92bed8><action>",
            "action-body" to "<#e6fff3><description><newline><#969696>Команда: /<command>",
            "action-run-label" to "<#2bba43>Выполнить",
            "favorite-add-label" to "<#f4bd6a>Добавить в избранное",
            "favorite-remove-label" to "<#f4bd6a>Убрать из избранного",
            "goals-short-label" to "<#f4bd6a>Чем заняться",
            "goals-tooltip" to "<#e6fff3>Подобрать игровые действия под вашу цель.",
            "goals-title" to "<#f4bd6a>Чем заняться",
            "goals-body" to "<#e6fff3>Выберите, чего хочется сейчас.<newline><#969696>Покажу несколько подходящих возможностей без лишнего списка.",
            "goal-earn-label" to "<#f4bd6a>Заработать",
            "goal-build-label" to "<#2bba43>Строить",
            "goal-explore-label" to "<#92bed8>Исследовать",
            "goal-fight-label" to "<#ff6b61>Сражаться",
            "goal-develop-label" to "<#92bed8>Развиваться",
            "goal-together-label" to "<#92bed8>Играть вместе",
            "goal-title" to "<#f4bd6a><goal>",
            "goal-body" to "<#e6fff3>Вот короткий набор подходящих действий.",
            "context-short-label" to "<#92bed8>Что рядом со мной",
            "context-tooltip" to "<#e6fff3>Мир, приват, предмет в руке и полезные действия.",
            "context-title" to "<#92bed8>Что рядом со мной",
            "context-body" to "<#92bed8>◆ <#969696>Мир  <#e6fff3><world><newline><#92bed8>◆ <#969696>Сервер  <#e6fff3><server><newline><#92bed8>◆ <#969696>Координаты  <#e6fff3><coordinates><newline><#2bba43>◆ <#969696>Приват  <#e6fff3><land><newline><#f4bd6a>◆ <#969696>В руке  <#e6fff3><item>",
            "context-item-label" to "<#f4bd6a>Предмет в руке",
            "item-tooltip" to "<#e6fff3>Рецепт, каталог, торговля и улучшения предмета.",
            "item-title" to "<#f4bd6a>Предмет в руке",
            "item-empty" to "<#e6fff3>Возьмите предмет в основную руку и откройте этот экран снова.",
            "item-body" to "<#f4bd6a><item><newline><#969696>Количество: <#e6fff3><amount><newline><#969696>Тип: <#e6fff3><kind>",
            "item-recipe-label" to "<#2bba43>Показать рецепт",
            "item-kind-vanilla" to "обычный",
            "item-kind-custom" to "дополнительный",
            "world-kind-vanilla" to "обычный мир",
            "world-kind-mining" to "мир добычи",
            "world-kind-biomes" to "мир новых биомов",
            "context-outside-privat" to "вне привата",
            "context-empty-hand" to "пустая рука",
            "onboarding-pending" to "есть незавершённый следующий шаг",
            "onboarding-clear" to "новых шагов обучения не видно",
            "requests-short-label" to "<#f4bd6a>Дела и запросы",
            "requests-tooltip" to "<#e6fff3>Обучение, задания, награды и игровые приглашения.",
            "requests-title" to "<#f4bd6a>Дела и запросы",
            "requests-body" to "<#e6fff3>Обучение: <hint><newline><#969696>Ответы ниже относятся к последнему входящему запросу.<newline>Награды и приглашения проверяются в своих разделах.",
            "check-command-label" to "<#92bed8>Проверить: <label>",
            "check-quests-label" to "<#92bed8>Проверить задания",
            "check-battle-pass-label" to "<#f4bd6a>Проверить боевой пропуск",
            "check-vote-label" to "<#f4bd6a>Проверить голосование",
            "check-events-label" to "<#92bed8>Открыть события",
            "check-duels-label" to "<#ff6b61>Открыть дуэли",
            "check-privat-label" to "<#92bed8>Проверить приваты",
            "request-tpa-accept-label" to "<#2bba43>Принять телепорт",
            "request-tpa-deny-label" to "<#ff6b61>Отклонить телепорт",
            "request-duel-accept-label" to "<#2bba43>Принять дуэль",
            "request-duel-deny-label" to "<#ff6b61>Отклонить дуэль",
            "search-loading" to "<#e6fff3>Сопоставляю запрос с вашими домами и игроками сети…",
            "problem-cannot-teleport-label" to "<#92bed8>Не телепортирует",
            "problem-cannot-claim-label" to "<#2bba43>Не получается заприватить",
            "problem-cannot-find-player-label" to "<#92bed8>Не вижу игрока",
            "problem-lost-item-label" to "<#f4bd6a>Не понимаю предмет",
            "problem-command-failed-label" to "<#ff6b61>Команда не работает",
            "diagnostic-body" to "<#e6fff3>Что удалось проверить:<newline><#969696><facts><newline><newline><#e6fff3>Выберите ближайший безопасный путь.",
            "fact-homes-ready-yes" to "список домов доступен",
            "fact-homes-ready-no" to "список домов ещё не проверен",
            "fact-husk-ready-yes" to "система телепортации доступна",
            "fact-husk-ready-no" to "система телепортации недоступна",
            "fact-known-world-yes" to "тип текущего мира определён",
            "fact-known-world-no" to "это особый мир",
            "fact-lands-ready-yes" to "система приватов доступна",
            "fact-lands-ready-no" to "система приватов недоступна",
            "fact-outside-land-yes" to "вы сейчас вне чужого привата",
            "fact-outside-land-no" to "вы уже на территории привата",
            "fact-land-owner-yes" to "вы владелец текущего привата",
            "fact-land-owner-no" to "вы не владелец текущего привата",
            "fact-network-list-ready-yes" to "поиск проверяет всю сеть серверов",
            "fact-network-list-ready-no" to "список игроков сети недоступен",
            "fact-held-item-yes" to "предмет находится в основной руке",
            "fact-held-item-no" to "основная рука пустая",
            "fact-server-known-yes" to "текущий сервер определён",
            "fact-server-known-no" to "текущий сервер не определён",
            "my-title" to "<#f4bd6a>Про меня",
            "my-loading" to "<#e6fff3>Собираю ваш профиль…",
            "my-identity" to "<#f4bd6a><player><newline><#969696>Сервер: <#92bed8><server><newline><#969696>Ранг: <#2bba43><rank>",
            "my-summary" to "<#969696>Баланс: <#f4bd6a><balance><newline><#969696>Дома: <#92bed8><homes>/<max_homes><newline><#969696>Поселения: <#92bed8><lands>",
            "my-location" to "<#969696>Мир: <#92bed8><world><newline><#969696>Координаты: <#e6fff3><x>, <y>, <z>",
            "my-error" to "<#e6fff3>Часть профиля сейчас недоступна. Быстрые разделы всё равно работают.",
            "my-homes-label" to "<#92bed8>Мои дома",
            "my-homes-tooltip" to "<#e6fff3>Сохранённые точки и перемещения.",
            "my-lands-label" to "<#92bed8>Мои приваты",
            "my-lands-tooltip" to "<#e6fff3>Территория, участники и настройки.",
            "my-rank-label" to "<#92bed8>Мой ранг",
            "my-rank-tooltip" to "<#e6fff3>Текущий ранг и следующие цели.",
            "my-jobs-label" to "<#f4bd6a>Мои работы",
            "my-jobs-tooltip" to "<#e6fff3>Профессии, уровни и заработок.",
            "my-quests-label" to "<#f4bd6a>Мои задания",
            "my-quests-tooltip" to "<#e6fff3>Активные задания и награды.",
            "my-skills-label" to "<#92bed8>Мои навыки",
            "my-skills-tooltip" to "<#e6fff3>Открыть навыки и их развитие.",
            "guide-title" to "<#f4bd6a>С чего начать",
            "guide-body" to "<#f4bd6a>1 · Стартовый набор<newline><#e6fff3>Получите первые инструменты и припасы.<newline><newline><#92bed8>2 · Выберите мир<newline><#e6fff3>Обычный мир, мир добычи или мир новых биомов.<newline><newline><#f4bd6a>3 · Начните зарабатывать<newline><#e6fff3>Выберите работу и получайте деньги за привычные действия.<newline><newline><#2bba43>4 · Дом и поселение<newline><#e6fff3>Сохраните точку дома и защитите территорию поселением.",
            "kit-label" to "<#f4bd6a>Получить набор",
            "vanilla-label" to "<#92bed8>Обычный мир",
            "mining-label" to "<#92bed8>Мир добычи",
            "biomes-label" to "<#92bed8>Мир новых биомов",
            "jobs-label" to "<#f4bd6a>Выбрать работу",
            "rules-label" to "<#92bed8>Правила",
            "commands-title" to "<#f4bd6a>Поиск",
            "commands-body" to "<#e6fff3>Опишите, что хотите сделать, обычной фразой.<newline><#969696>Поиск понимает формы слов, близкие значения и небольшие опечатки.",
            "search-input" to "<#fff0d8>Что вы хотите сделать?",
            "search-label" to "<#f4bd6a>Найти",
            "search-tooltip" to "<#fff0d8>Например: удалить поселение, перенести дом, добавить друга.",
            "search-title" to "<#f4bd6a>Результаты поиска",
            "search-body" to "<#969696>Запрос  <#e6fff3><query><newline><#969696>Найдено  <#e6fff3><count>",
            "search-empty" to "<#fff0d8>Не понял запрос. Опишите действие и объект: «перенести дом» или «добавить игрока».",
            "search-result-tooltip" to "<#fff0d8><description><newline><#8d7768>Открыть нужный раздел",
            "category-start-label" to "<#f4bd6a>Начало игры",
            "category-travel-label" to "<#92bed8>Телепортация",
            "category-protection-label" to "<#92bed8>Защита",
            "category-trade-label" to "<#f4bd6a>Торговля",
            "category-progress-label" to "<#92bed8>Развитие",
            "category-social-label" to "<#92bed8>Общение и сервер",
            "category-activities-label" to "<#f4bd6a>Активности",
            "category-technology-label" to "<#92bed8>Технологии",
            "category-settings-label" to "<#92bed8>Настройки",
            "category-activities-tooltip" to "<#e6fff3>События, дуэли, данжи и фермы.",
            "category-technology-tooltip" to "<#e6fff3>Предметы, зачарования, механизмы и транспорт.",
            "category-settings-tooltip" to "<#e6fff3>Чат, эффекты и личные переключатели.",
            "category-trade-tooltip" to "<#e6fff3>Магазины, быстрая продажа и аукцион.",
            "category-progress-tooltip" to "<#e6fff3>Ранг, работы, задания и навыки.",
            "category-social-tooltip" to "<#e6fff3>Голосование и выбор режима чата.",
            "category-start-title" to "<#f4bd6a>Начало игры",
            "category-travel-title" to "<#92bed8>Телепортация",
            "category-protection-title" to "<#92bed8>Защита",
            "category-trade-title" to "<#f4bd6a>Торговля",
            "category-progress-title" to "<#92bed8>Развитие",
            "category-social-title" to "<#92bed8>Общение и сервер",
            "category-activities-title" to "<#f4bd6a>Активности",
            "category-technology-title" to "<#92bed8>Технологии",
            "category-settings-title" to "<#92bed8>Настройки",
            "settings-body" to "<#969696>Чат: <#e6fff3><chat><newline><#969696>След: <#e6fff3><trails><newline><#969696>Ускорение: <#e6fff3><boost><newline><newline><#969696>После переключения экран обновится.",
            "state-on" to "включено",
            "state-off" to "выключено",
            "state-unknown" to "выберите состояние",
            "players-title" to "<#92bed8>Игроки",
            "players-body" to "<#e6fff3>Игроки: <#f4bd6a><total><newline><#969696>Где ищем: <#e6fff3><scope><newline><#969696>Страница <page>/<pages> · на экране <count>",
            "players-empty" to "<#969696>Игроков по этому фильтру нет.<newline>Измените ник или переключитесь на всю сеть.",
            "players-input" to "<#e6fff3>Ник игрока",
            "players-search-label" to "<#f4bd6a>Найти игрока",
            "players-search-tooltip" to "<#969696>Применить фильтр",
            "player-label" to "<#92bed8><player>",
            "player-tooltip" to "<#969696>Сервер: <#92bed8><server>",
            "player-server-unknown" to "неизвестен",
            "player-title" to "<#92bed8><player>",
            "player-body" to "<#e6fff3><player><newline><#969696>Сейчас на сервере <#92bed8><server><#969696>.<newline><newline><#e6fff3>Выберите действие.",
            "player-tpa-label" to "<#92bed8>Телепортироваться к нему",
            "player-tpahere-label" to "<#92bed8>Позвать к себе",
            "player-message-label" to "<#2bba43>Написать сообщение",
            "player-pay-label" to "<#f4bd6a>Перевести деньги",
            "player-duel-label" to "<#ff6b61>Вызвать на дуэль",
            "player-invite-label" to "<#2bba43>Пригласить в поселение",
            "message-title" to "<#2bba43>Сообщение · <player>",
            "message-body" to "<#e6fff3>Напишите короткое личное сообщение для <#92bed8><player><#e6fff3>.",
            "message-input" to "<#e6fff3>Текст сообщения",
            "message-send-label" to "<#2bba43>Отправить",
            "invalid-message" to "<#ff6b61>Сообщение должно занимать от 1 до 128 символов и быть в одну строку.",
            "pay-title" to "<#f4bd6a>Перевод · <player>",
            "pay-body" to "<#e6fff3>Укажите сумму. Перед переводом будет подтверждение.",
            "pay-input" to "<#e6fff3>Сумма",
            "pay-continue-label" to "<#f4bd6a>Проверить перевод",
            "pay-confirm-title" to "<#f4bd6a>Подтверждение перевода",
            "pay-confirm-body" to "<#e6fff3>Перевести <#f4bd6a><amount> <#e6fff3>игроку <#92bed8><player><#e6fff3>?",
            "pay-confirm-label" to "<#ff6b61>Подтвердить перевод",
            "invalid-amount" to "<#ff6b61>Введите положительную сумму, не больше двух знаков после запятой.",
            "recovery-label" to "<#ff6b61>Что случилось?",
            "recovery-tooltip" to "<#e6fff3>Быстрые выходы, если вы застряли или потерялись.",
            "recovery-title" to "<#ff6b61>Что случилось?",
            "recovery-body" to "<#e6fff3>Выберите самое похожее действие.<newline><#969696>Если не помогло — откройте поиск и опишите проблему своими словами.",
            "category-body" to "<#e6fff3>Выберите действие. Подробности — при наведении.<newline><#969696>После закрытия игрового инвентаря вы вернётесь сюда.",
            "command-label" to "<#e6fff3><label>",
            "command-vote-label" to "<#f4bd6a>Голосование",
            "command-chat-global-label" to "<#92bed8>Глобальный чат",
            "command-chat-local-label" to "<#92bed8>Локальный чат",
            "command-lands-borders-label" to "<#92bed8>Границы привата",
            "command-trails-on-label" to "<#2bba43>Включить след",
            "command-trails-off-label" to "<#f4bd6a>Выключить след",
            "command-trails-boost-on-label" to "<#f4bd6a>След при ускорении",
            "command-trails-boost-off-label" to "<#f4bd6a>Убрать след ускорения",
            "command-particles-label" to "<#92bed8>Частицы",
            "command-tpa-ignore-label" to "<#92bed8>Запросы телепорта",
            "command-tooltip" to "<#fff0d8><description><newline><#8d7768>/<command>",
            "travel-title" to "<#92bed8>Телепортация",
            "travel-loading" to "<#fff0d8>Загружаю ваши дома…",
            "travel-body" to "<#8d7768>Дома: <#f4bd6a><homes>/<max_homes><newline><#fff0d8>Выберите дом или другое направление.",
            "travel-empty" to "<#fff0d8>У вас пока нет домов. Создайте первый в текущей точке.",
            "travel-limit" to "<#8d7768>Свободных слотов нет. Удалите или перенесите существующий дом.",
            "travel-error" to "<#fff0d8>Дома сейчас не загрузились, но остальные способы телепортации доступны.",
            "home-label" to "<#92bed8><home>",
            "home-tooltip" to "<#fff0d8><server> · <world><newline><#8d7768><x>, <y>, <z>",
            "create-home-label" to "<#f4bd6a>Новый дом",
            "create-home-tooltip" to "<#fff0d8>Сохранить текущую точку.",
            "home-create-title" to "<#f4bd6a>Новый дом",
            "home-create-body" to "<#fff0d8>Введите короткое имя без пробелов.<newline><#8d7768>Дом будет создан в вашей текущей точке.",
            "home-name-input" to "<#fff0d8>Название дома",
            "home-create-submit" to "<#f4bd6a>Создать",
            "home-title" to "<#92bed8>Дом · <home>",
            "home-body" to "<#8d7768>Сервер: <#fff0d8><server><newline><#8d7768>Мир: <#fff0d8><world><newline><#8d7768>Координаты: <#fff0d8><x>, <y>, <z>",
            "home-teleport-label" to "<#f4bd6a>Телепортироваться",
            "home-teleport-tooltip" to "<#fff0d8>Переместиться в сохранённую точку.",
            "home-relocate-label" to "<#fff0d8>Перенести сюда",
            "home-relocate-tooltip" to "<#fff0d8>Заменить точку вашим текущим положением. Потребуется подтверждение.",
            "home-delete-label" to "<#c42323><bold>Удалить дом",
            "home-delete-tooltip" to "<#fff0d8>Удалить сохранённую точку. Потребуется подтверждение.",
            "home-relocate-title" to "<#f4bd6a>Перенести · <home>",
            "home-relocate-body" to "<#fff0d8>Заменить сохранённую точку дома <#f4bd6a><home> <#fff0d8>вашим текущим положением?",
            "home-relocate-confirm" to "<#f4bd6a>Перенести точку",
            "home-delete-title" to "<#ff6b61>Удаление · <home>",
            "home-delete-body" to "<#c42323><bold>Это необратимое действие.<newline><#fff0d8>Дом <#f4bd6a><home> <#fff0d8>будет удалён.",
            "home-delete-confirm" to "<#c42323><bold>Удалить навсегда",
            "warps-label" to "<#92bed8>Варпы игроков",
            "spawn-label" to "<#92bed8>Спавн",
            "rtp-label" to "<#92bed8>Случайное место",
            "back-command-label" to "<#92bed8>На прежнее место",
            "stuck-label" to "<#f4bd6a>Выбраться на спавн",
            "public-homes-label" to "<#92bed8>Публичные дома",
            "public-homes-tooltip" to "<#fff0d8>Посмотреть открытые дома игроков.",
            "invalid-home" to "<#c42323>Имя дома: до 32 букв, цифр, _ или - без пробелов.",
            "action-failed" to "<#c42323>Команда не выполнилась. Попробуйте ещё раз или сообщите администрации.",
        )

        internal val COMMANDS = linkedMapOf(
            "menu" to HelpCenterCommandText("Главное меню", "Все игровые разделы", "разделы сервер mm"),
            "kit" to HelpCenterCommandText("Набор новичка", "Получить стартовые предметы", "старт начало вещи"),
            "rules" to HelpCenterCommandText("Правила", "Правила игрового сервера", "запрещено можно"),
            "tutorial" to HelpCenterCommandText("Обучение", "Вернуться к обучению", "гайд начало"),
            "warps" to HelpCenterCommandText("Варпы игроков", "Публичные точки игроков", "телепорт точки"),
            "spawn" to HelpCenterCommandText("Спавн", "Вернуться на спавн", "телепорт начало"),
            "rtp" to HelpCenterCommandText("Случайное место", "Телепорт в случайную безопасную точку", "рандом ресурсы"),
            "back" to HelpCenterCommandText("Вернуться назад", "Вернуться к прошлой позиции", "телепорт смерть"),
            "stuck" to HelpCenterCommandText("Выбраться на спавн", "Аварийный возврат со сложного места", "застрял помощь"),
            "vanilla" to HelpCenterCommandText("Обычный мир", "Перейти в обычный мир выживания", "ванильный стандартный мир ресурсы база"),
            "mining" to HelpCenterCommandText("Мир добычи", "Перейти в обновляемый ресурсный мир", "шахта ресурсы"),
            "biomes" to HelpCenterCommandText("Мир новых биомов", "Перейти в мир выживания с новыми биомами", "новые биомы необычный мир база"),
            "privat" to HelpCenterCommandText("Приват", "Создание и защита территории", "земля поселение lands приват защита"),
            "events" to HelpCenterCommandText("События", "Активные серверные события", "ивенты события награды"),
            "duels" to HelpCenterCommandText("Дуэли", "Сразиться с другим игроком", "пвп бой поединок"),
            "battle-pass" to HelpCenterCommandText("Боевой пропуск", "Задания и награды сезона", "бп сезон пропуск награды"),
            "giveaways" to HelpCenterCommandText("Розыгрыши", "Активные розыгрыши сервера", "giveaway конкурс приз"),
            "dungeons" to HelpCenterCommandText("Данжи", "Меню данжей и боссов", "данж подземелье боссы элитные мобы"),
            "dungeon-portals" to HelpCenterCommandText("Порталы данжей", "Телепорт к порталам приключений", "данж подземелье портал гильдия"),
            "farms" to HelpCenterCommandText("Фермы", "Управление игровыми фермами", "ферма урожай животные"),
            "shops" to HelpCenterCommandText("Магазины", "Магазины игроков и сервера", "рынок купить продать"),
            "sell" to HelpCenterCommandText("Быстрая продажа", "Продать подходящие предметы", "деньги рынок"),
            "auction" to HelpCenterCommandText("Аукцион", "Торговля предметами между игроками", "ah рынок купить продать"),
            "bank" to HelpCenterCommandText("Банк", "Открыть личный банковский счёт", "деньги счет вклад"),
            "investments" to HelpCenterCommandText("Инвестиции", "Портфель и рынок акций", "акции биржа портфель"),
            "rank" to HelpCenterCommandText("Ранги", "Текущий ранг и следующие цели", "уровень развитие"),
            "rankup" to HelpCenterCommandText("Повысить ранг", "Проверить требования повышения", "уровень развитие"),
            "jobs" to HelpCenterCommandText("Работы", "Профессии и заработок", "деньги профессия"),
            "quests" to HelpCenterCommandText("Задания", "Активные задания и награды", "квест развитие"),
            "skills" to HelpCenterCommandText("Навыки", "Навыки и их развитие", "auraskills способности развитие"),
            "slimefun" to HelpCenterCommandText("Книга технологий", "Открыть справочник Slimefun", "slimefun сф механизмы рецепты"),
            "items" to HelpCenterCommandText("Новые предметы", "Каталог дополнительных предметов", "itemsadder предметы рецепты"),
            "enchants" to HelpCenterCommandText("Зачарования", "Список особых зачарований", "энчанты чары магия"),
            "enchanter" to HelpCenterCommandText("Зачарователь", "Магазин особых зачарований", "купить чары энчанты"),
            "builder" to HelpCenterCommandText("Инструменты строителя", "Получить книгу инструментов", "стройка билдер блоки"),
            "mounts" to HelpCenterCommandText("Транспорт", "Коллекция ездовых существ", "маунты транспорт питомцы"),
            "lands-borders" to HelpCenterCommandText("Границы поселения", "Показать границы участка", "чанки границы приват"),
            "trails-on" to HelpCenterCommandText("Включить след", "Показывать выбранный визуальный след", "trail частицы эффект"),
            "trails-off" to HelpCenterCommandText("Выключить след", "Скрыть визуальный след", "trail частицы эффект"),
            "trails-boost-on" to HelpCenterCommandText("След при ускорении", "Включить эффект быстрого движения", "trail boost ускорение"),
            "trails-boost-off" to HelpCenterCommandText("Убрать след ускорения", "Выключить эффект быстрого движения", "trail boost ускорение"),
            "particles" to HelpCenterCommandText("Частицы", "Включить или выключить личные частицы", "эффекты партиклы"),
            "tpa-ignore" to HelpCenterCommandText("Запросы телепорта", "Включить или выключить входящие запросы", "tpa запросы игнор"),
            "vote" to HelpCenterCommandText(
                "Голосование",
                "Открыть ссылки для голосования за сервер",
                "vote votes голос голосование рейтинг награда мониторинг",
            ),
            "chat-global" to HelpCenterCommandText(
                "Глобальный чат",
                "Переключить режим на глобальный чат",
                "чат глобальный общий g всем писать",
            ),
            "chat-local" to HelpCenterCommandText(
                "Локальный чат",
                "Переключить режим на локальный чат рядом",
                "чат локальный рядом l местный писать",
            ),
        )

        internal val INTENTS = linkedMapOf(
            "context" to HelpCenterIntentText("Что рядом со мной", "Мир, координаты и текущий приват.", "рядом местоположение координаты текущий мир"),
            "requests" to HelpCenterIntentText("Входящие запросы", "Ответы на запросы и проверка наград.", "входящие запросы принять отклонить награды приглашения"),
            "held-item" to HelpCenterIntentText("Предмет в руке", "Рецепт, каталог и торговля.", "предмет в руке рецепт что это назначение"),
            "goals" to HelpCenterIntentText("Чем заняться", "Подбор занятий по вашей цели.", "чем заняться скучно заработать строить исследовать играть вместе"),
            "favorites" to HelpCenterIntentText("Избранное", "Закреплённые и последние действия.", "избранное недавнее закрепить быстрый доступ любимое"),
            "my" to HelpCenterIntentText(
                "Про меня",
                "Открыть личный профиль, дома, земли и прогресс",
                "мой профиль баланс деньги координаты где я мои данные",
            ),
            "player-find" to HelpCenterIntentText(
                "Найти игрока",
                "Открыть действия с игроками онлайн на всей сети",
                "игрок друг написать другу личка лс msg телепорт сообщение перевод дуэль пригласить",
            ),
            "recovery" to HelpCenterIntentText(
                "Что случилось?",
                "Быстрые действия, если вы застряли или потерялись",
                "застрял потерялся умер не работает проблема помощь",
            ),
            "home-create" to HelpCenterIntentText(
                "Создать дом",
                "Сохранить текущую точку как новый дом",
                "поставить дом создать хом sethome сохранить точку",
            ),
            "home-move" to HelpCenterIntentText(
                "Перенести дом",
                "Выбрать дом и заменить его сохранённую точку",
                "передвинуть переместить перенести точку дома edithome",
            ),
            "home-delete" to HelpCenterIntentText(
                "Удалить дом",
                "Выбрать сохранённый дом для удаления",
                "удалить стереть снести дом хом delhome",
            ),
            "land-create" to HelpCenterIntentText(
                "Создать поселение",
                "Открыть приват и создать новое поселение",
                "создать основать сделать поселение землю приват",
            ),
            "land-delete" to HelpCenterIntentText(
                "Удалить поселение",
                "Открыть приват и выбрать поселение для удаления",
                "как удалить распустить закрыть снести поселение землю приват lands",
            ),
            "land-invite" to HelpCenterIntentText(
                "Добавить игрока в поселение",
                "Выбрать поселение и пригласить участника",
                "добавить пригласить позвать друга игрока участника доверить trust",
            ),
            "land-remove" to HelpCenterIntentText(
                "Исключить игрока из поселения",
                "Выбрать поселение и убрать участника",
                "удалить выгнать исключить убрать игрока участника untrust",
            ),
            "land-main-block" to HelpCenterIntentText(
                "Перенести блок поселения",
                "Открыть управление главным блоком поселения",
                "перенести передвинуть переместить блок колокол костер mainblock",
            ),
            "land-claim" to HelpCenterIntentText(
                "Расширить территорию",
                "Открыть приват и управление участками",
                "заприватить занять добавить чанк участок территорию claim",
            ),
        )
    }
}
